// https://gist.github.com/zats/35b2f5bbe5ae72a2efb7793098be10dd

export const EMOJIS = {
  '💍': ['diamond ', ' engagement ring ', ' diamond ring ', ' diamond rings ', ' diamonds ', ' engagement rings'],
  '🆎': ['blood type AB'],
  '❣': ['heart'],
  // '🇱🇨': ['Saint Lucia ', ' Saint Lucian flag'],
  // '🇮🇪': ['Ireland ', ' Irish flag'],
  // '🇨🇮': ['Côte d’Ivoire ', ' Ivory Coast ', ' Ivorian flag'],
  '💎': ['diamond ', ' gem ', ' gemstone ', ' jewel ', ' diamonds ', ' gems ', ' gemstones ', ' jewels'],
  '☠️': ['skull and crossbones ', ' poison ', ' poisonous'],
  '👩‍💻': [
    'technology worker ',
    ' tech worker ',
    ' technologist ',
    ' techie ',
    ' IT worker ',
    ' Apple genius ',
    ' woman in technology ',
    ' woman tech worker ',
    ' woman technologist ',
    ' woman IT worker ',
    ' woman in IT ',
    ' woman Apple genius',
  ],
  '👷‍♀️': ['construction worker ', ' construction workers'],
  '💐': ['bouquet ', ' flower ', ' tulip ', ' bouquets ', ' flowers ', ' tulips'],
  '✌️': ['peace ', ' peace out ', ' dueces'],
  '🏴󠁧󠁢󠁷󠁬󠁳󠁿': ['Wales ', ' Welsh flag'],
  '💓': ['heart ', ' heart beating'],
  '🆔': ['ID ', ' identification'],
  '💔': ['heart ', ' broken heart'],
  '🇫🇮': ['Finland ', ' Finnish flag'],
  '🇨🇰': ['Cook Islands ', ' Cook Island flag'],
  '💕': ['love ', ' hearts'],
  '🆖': ['no good'],
  '👩‍💼': [
    'office worker ',
    ' insurance agent ',
    ' saleswoman ',
    ' paper pusher ',
    ' clerical worker ',
    ' admin ',
    ' administrative worker ',
    ' secretary ',
    ' CEO ',
    ' CFO ',
    ' CPA ',
    ' CTO ',
    ' woman office worker ',
    ' woman insurance agent ',
    ' woman clerical worker ',
    ' woman admin ',
    ' woman administrative worker ',
    ' woman secretary ',
    ' woman CEO ',
    ' woman CFO ',
    ' woman CPA ',
    ' woman CTO',
  ],
  '🏴󠁧󠁢󠁳󠁣󠁴󠁿': ['Scotland ', ' Scottish flag'],
  '👩‍🚒': ['firefighter ', ' woman firefighter'],
  '👩‍🎓': [
    'student ',
    ' graduate ',
    ' pupil ',
    ' woman student ',
    ' woman graduate ',
    ' woman pupil ',
    ' graduation ',
    ' graduation day ',
    ' alumnae ',
    ' alumna ',
    ' alumnus ',
    ' alumni ',
    ' alma mater',
  ],
  '💖': ['love ', ' heart ', ' twinkling'],
  '🆗': ['okay ', ' OK'],
  '✈️': ['plane ', ' airplane ', ' planes ', ' airplanes'],
  '💗': ['love ', ' heart ', ' heart beating ', ' heartbeats ', ' heartbeat'],
  '🇫🇯': ['Fiji ', ' Fijian flag'],
  '🇨🇱': ['Chile ', ' Chilean flag'],
  '💘': ['love'],
  '💙': ['heart'],
  '💚': ['heart'],
  '☘️': ['Irish ', ' shamrock ', ' three leaf clover ', ' three leaf clovers'],
  '🗳': ['ballot box ', ' ballot boxes ', ' vote ', ' votes ', ' voted ', ' voting ', ' election'],
  '💛': ['heart'],
  // '🇫🇰': ['Falkland Islands ', ' Falkland Island flag'],
  // '🇨🇲': ['Cameroon ', ' Cameroonian flag'],
  '⛹️‍♂️': ['basketball player ', ' basketball players ', ' baller ', ' ballers ', ' man playing basketball'],
  '💜': ['heart'],
  // '🇺🇦': ['Ukraine ', ' Ukrainian flag'],
  '💝': ['heart ', ' present ', ' gift'],
  '💞': ['heart'],
  // '🇨🇳': ['China ', ' Chinese flag ', ' People’s Republic of China ', ' Peoples Republic of China'],
  '💟': ['heart'],
  '🙅‍♀️': [
    'not gonna happen ',
    ' not going to happen ',
    ' poor choice ',
    ' a no go ',
    ' denied ',
    ' rejected ',
    ' no deal',
  ],
  '🏊‍♂️': ['pool ', ' swim ', ' swimmer ', ' swimming ', ' swimmers ', ' man swimming'],
  '☔️': ['rain ', ' umbrella ', ' raining ', ' drops ', ' storm ', ' umbrellas ', ' purple rain'],
  '💡': ['bulb ', ' bulbs ', ' light bulb ', ' idea ', ' light bulbs ', ' light ', ' ideas'],
  '🗺': ['map ', ' world map ', ' world'],
  '⛅️': ['cloud ', ' cloudy ', ' clouds'],
  '💢': ['anger sign'],
  // '🇷🇪': ['Réunion ', ' Réunionese flag ', ' Réunionnais flag'],
  // '🇱🇮': ['Liechtenstein ', ' Liechtenstein flag'],
  '🗻': ['Mount Fuji'],
  // '🇫🇲': ['Micronesia ', ' Micronesian flag'],
  // '🇨🇴': ['Colombia ', ' Colombian flag'],
  '💤': [
    'sleeping ',
    ' zzz ',
    ' Zs ',
    ' sleep ',
    ' napping ',
    ' nap ',
    ' sleepy ',
    ' asleep ',
    ' tired ',
    ' exhausted ',
    ' snoring ',
    ' drowsy',
  ],
  '🗽': ['Statue of Liberty ', ' liberty'],
  '👨‍🎤': [
    'singer ',
    ' musician ',
    ' artist ',
    ' musical artist ',
    ' man singer ',
    ' man musician ',
    ' man artist ',
    ' man musical artist ',
    ' diva ',
    ' vocalist ',
    ' minstrel ',
    ' soloist',
  ],
  '💥': ['POW ', ' BAM ', ' boom ', ' explosion'],
  // '🇮🇱': ['Israel ', ' Israeli flag'],
  '💦': ['sweat ', ' water ', ' water droplets ', ' water drops'],
  '👩‍🔧': ['mechanic ', ' technician ', ' woman mechanic ', ' woman technician'],
  '🗿': ['moai ', ' moyai ', ' Easter Island ', ' Easter Island statue ', ' Easter Island statues'],
  '🌀': ['cyclone ', ' cyclones ', ' hurricane ', ' hurricanes'],
  '💆‍♂️': ['massage ', ' massages ', ' man massage'],
  '💧': ['water ', ' sweat ', ' droplet ', ' droplets ', ' drip ', ' water drop'],
  '😀': [
    'happy ',
    ' smile ',
    ' smiley ',
    ' smiley face ',
    ' so happy ',
    ' that’s great ',
    ' so great ',
    ' yay ',
    ' hooray ',
    ' hurrah ',
    ' cheerful ',
    ' delighted ',
    ' joyful ',
    ' pleased',
  ],
  '💨': ['vape ', ' gust ', ' fart ', ' smoke ', ' wind ', ' fast ', ' gusts ', ' farts'],
  '😁': [
    'braces ',
    ' happy ',
    ' smiley face ',
    ' too funny ',
    ' funny ',
    ' so happy ',
    ' that’s great ',
    ' so great ',
    ' yay ',
    ' hooray ',
    ' hurrah ',
    ' hoorah ',
    ' thrilled ',
    ' in a good mood ',
    ' cheerful ',
    ' delighted ',
    ' joyful ',
    ' overjoyed ',
    ' pleased ',
    ' squinting smiley',
  ],
  '🌂': ['umbrella ', ' umbrellas'],
  // '🇱🇰': ['Sri Lanka ', ' Sri Lankan flag'],
  // '🇮🇲': ['Isle Of Man ', ' Manx flag'],
  '🤽‍♀️': ['water polo ', ' water polo player ', ' playing water polo ', ' water sport ', ' woman playing water polo'],
  '🏃‍♂️': [
    'runner ',
    ' jogger ',
    ' jogging ',
    ' run ',
    ' running ',
    ' runners ',
    ' joggers ',
    ' get away ',
    ' man running',
  ],
  '😂': [
    'so funny ',
    ' too funny ',
    ' hilarious ',
    ' lol ',
    ' cracking up ',
    ' cracked up ',
    ' crack me up ',
    ' dying laughing ',
    ' tears of joy ',
    ' tears of happiness ',
    ' funny ',
    ' funniest ',
    ' laugh ',
    ' haha ',
    ' hehe ',
    ' crying smiley ',
    ' smiley face ',
    ' laughing ',
    ' lmao ',
    ' lolz ',
    ' lols ',
    ' lulz ',
    ' rotfl ',
    ' rotflmao',
  ],
  '🌃': ['skyline ', ' city'],
  // '🇫🇴': ['Faroe Islands ', ' Faroe Island flag'],
  '😃': [
    'happy ',
    ' smile ',
    ' smiley ',
    ' smiley face ',
    ' so happy ',
    ' that’s great ',
    ' so great ',
    ' yay ',
    ' hooray ',
    ' hurrah ',
    ' hoorah ',
    ' cheerful ',
    ' delighted ',
    ' joyful ',
    ' pleased',
  ],
  '💩': ['poop ', ' poo ', ' doo doo ', ' dookie ', ' crap ', ' caca ', ' turd ', ' poops ', ' turds'],
  '💪': [
    'bicep ',
    ' dumbbell ',
    ' working out ',
    ' strong ',
    ' biceps ',
    ' dumbbells ',
    ' work out ',
    ' works out ',
    ' worked out ',
    ' flex ',
    ' strong arm ',
    ' pull-up ',
    ' guns ',
    ' muscles',
  ],
  '💫': ['star ', ' comet ', ' comets'],
  '😄': [
    'happy ',
    ' smiley face ',
    ' too funny ',
    ' funny ',
    ' so happy ',
    ' that’s great ',
    ' so great ',
    ' yay ',
    ' hooray ',
    ' hurrah ',
    ' hoorah ',
    ' thrilled ',
    ' in a good mood ',
    ' cheerful ',
    ' delighted ',
    ' joyful ',
    ' overjoyed ',
    ' pleased ',
    ' squinting smiley',
  ],
  '🌅': ['sunset ', ' sunrise ', ' sun postcard ', ' sunsets ', ' sunrises'],
  '😅': [
    'sweating ',
    ' phew ',
    ' relieved ',
    ' thank goodness ',
    ' thankfully ',
    ' what a relief ',
    ' that’s a relief',
  ],
  '🌆': ['cityscape'],
  // '🇮🇳': ['India ', ' Indian flag'],
  // '🇨🇷': ['Costa Rica ', ' Costa Rican flag'],
  '💭': [
    'thought ',
    ' chat ',
    ' daydream ',
    ' thought balloon ',
    ' daydreams ',
    ' thoughts ',
    ' think ',
    ' thinking ',
    ' thought bubble',
  ],
  '⚽️': ['soccer ', ' soccer ball ', ' soccer balls ', ' ball ', ' balls'],
  '😆': [
    'happy ',
    ' lol ',
    ' so funny ',
    ' too funny ',
    ' laughing ',
    ' lmao ',
    ' lolz ',
    ' lols ',
    ' lulz ',
    ' rotfl ',
    ' rotflmao ',
    ' excited ',
    ' cracking up ',
    ' cracked up ',
    ' crack me up ',
    ' hilarious ',
    ' funny ',
    ' funniest ',
    ' laugh ',
    ' so excited ',
    ' haha ',
    ' yay ',
    ' hooray ',
    ' smiley ',
    ' smiley face',
  ],
  '👨‍⚖️': [
    'judge ',
    ' court room ',
    ' moderator ',
    ' marshal ',
    ' justice of the peace ',
    ' legal official ',
    ' adjudicator ',
    ' judicial system ',
    ' justices ',
    ' man judge',
  ],
  '💮': ['white flower ', ' white flowers'],
  '😇': [
    'angel ',
    ' halo ',
    ' innocent ',
    ' halo smiley ',
    ' you’re welcome ',
    ' my pleasure ',
    ' it wasn’t me ',
    ' halo emoji',
  ],
  '🌈': ['rainbow ', ' rainbows'],
  '💯': ['one hundred ', ' 100'],
  // '🇺🇬': ['Uganda ', ' Ugandan flag'],
  // '🇮🇴': ['British Indian Ocean Territory ', ' BIOT flag'],
  '💰': ['money ', ' cash ', ' pay'],
  '😉': [
    'wink ',
    ' winking ',
    ' winking smiley ',
    ' winking emoji ',
    ' hehe ',
    ' heehee ',
    ' I got you ',
    ' don’t worry ',
    ' no worries ',
    ' you’re welcome ',
    ' you’re very welcome ',
    ' good luck ',
    ' amazing ',
    ' enjoy',
  ],
  '🌊': ['ocean ', ' sea ', ' surf ', ' tsunami ', ' waves ', ' tsunamis ', ' wave ', ' oceans'],
  '😊': [
    'happy ',
    ' blushing ',
    ' blushing emoji ',
    ' blushing smiley ',
    ' so good ',
    ' you’re welcome ',
    ' you’re very welcome ',
    ' thank you ',
    ' thank you so much ',
    ' that’s nice ',
    ' lovely ',
    ' excited ',
    ' yay ',
    ' can’t wait ',
    ' love it ',
    ' enjoy ',
    ' smile ',
    ' smiley ',
    ' smiley face',
  ],
  '🌋': ['volcano ', ' volcanos ', ' volcanoes ', ' eruption'],
  '😋': [
    'delicious ',
    ' yummy ',
    ' nom nom ',
    ' nomnom ',
    ' tasty ',
    ' yum ',
    ' goofy ',
    ' hungry ',
    ' licking lips ',
    ' licking my lips ',
    ' tongue smiley',
  ],
  '🌌': [
    'starry night ',
    ' sky ',
    ' galaxy ',
    ' constellations ',
    ' starry nights ',
    ' skies ',
    ' galaxies ',
    ' constellation',
  ],
  '💳': ['credit card ', ' credit cards ', ' debit card ', ' debit cards'],
  // '🇫🇷': ['France ', ' French flag'],
  '😌': ['relieved ', ' sounds good ', ' relaxed ', ' relaxing ', ' happy'],
  '🌍': ['globe ', ' world ', ' planet'],
  '💴': ['yen ', ' cash ', ' money ', ' currency'],
  '😍': [
    'love it ',
    ' in love ',
    ' love smiley ',
    ' I love you ',
    ' I love them ',
    ' I love him ',
    ' I love her ',
    ' in love with ',
    ' it’s beautiful ',
    ' you’re beautiful ',
    ' so beautiful ',
    ' my love ',
    ' crushing on ',
    ' I’m crushing ',
    ' love you',
  ],
  '🌎': ['globe ', ' world ', ' planet'],
  '👨‍🌾': ['farmer ', ' farmer joe ', ' Old Mc’Donald ', ' man farmer'],
  '💵': ['dollar ', ' cash ', ' money ', ' dollars'],
  '😎': [
    'sunglasses ',
    ' cool ',
    ' sunglasses on ',
    ' smiling face with sunglasses ',
    ' sunglasses emoji ',
    ' sunglasses smiley ',
    ' stunner shades ',
    ' sunny ',
    ' cool kid ',
    ' ballin ',
    ' chillin ',
    ' cool guy ',
    ' cool dude ',
    ' cool chick ',
    ' cool girl ',
    ' baller ',
    ' awesome ',
    ' relaxing ',
    ' relaxed ',
    ' no stress',
  ],
  '🌏': ['globe ', ' planet ', ' earth'],
  '💶': ['euro ', ' euros ', ' euro banknotes ', ' money ', ' cash'],
  '🧝‍♀️': ['elf ', ' woman elf ', ' elves ', ' woman elves ', ' Galadriel ', ' Arwen'],
  // '🇴🇲': ['Oman ', ' Omani flag'],
  '😏': ['smirk ', ' smirking ', ' mischievous ', ' heheh'],
  // '🇮🇶': ['Iraq ', ' Iraqi flag'],
  '🧚‍♂️': ['man fairy ', ' man fairies ', ' fairy ', ' fairies ', ' pixie ', ' pixies'],
  '😐': [
    'um ',
    ' straight face ',
    ' blank face ',
    ' umm ',
    ' blanked ',
    ' idk ',
    ' unamused ',
    ' seriously ',
    ' sorry ',
    ' unsure ',
    ' confused ',
    ' blankly ',
    ' apathetic ',
    ' bored ',
    ' unenthused ',
    ' unenthusiastic ',
    ' indifferent ',
    ' conflicted ',
    ' unnerved ',
    ' vacant expression ',
    ' blank expression ',
    ' no emotion ',
    ' emotionless',
  ],
  '🌑': ['moon'],
  // '🇨🇺': ['Cuba ', ' Cuban flag'],
  '💷': ['money ', ' cash ', ' sterling pounds ', ' British pounds ', ' quid'],
  '💸': ['cash ', ' money'],
  '😑': [
    'bored ',
    ' annoyed ',
    ' ugh ',
    ' tired ',
    ' sleepy ',
    ' resigned ',
    ' not feeling it ',
    ' unamused ',
    ' seriously ',
    ' straight face ',
    ' blank face ',
    ' blankly ',
    ' apathetic ',
    ' unenthused ',
    ' unenthusiastic ',
    ' indifferent ',
    ' expressionless ',
    ' hmph',
  ],
  '🤐': [
    'shut up ',
    ' zip it ',
    ' be quiet ',
    ' shut your mouth ',
    ' lips are sealed ',
    ' mouth shut ',
    ' lips sealed ',
    ' mute',
  ],
  '🌒': ['moon'],
  '🤑': [
    'money ',
    ' money face ',
    ' money emoji ',
    ' money smiley ',
    ' filthy rich ',
    ' ballin ',
    ' skrilla ',
    ' cash rollin ',
    ' skrillz ',
    ' cash money ',
    ' seeing dollar signs ',
    ' rich emoji ',
    ' rich people ',
    ' baller',
  ],
  '😒': [
    'not amused ',
    ' lame ',
    ' boo ',
    ' unamused ',
    ' seriously ',
    ' bad mood ',
    ' in a funk ',
    ' annoyed ',
    ' unenthused ',
    ' unenthusiastic ',
    ' suspicious ',
    ' wary ',
    ' unnerved',
  ],
  '🌓': ['moon'],
  // '🇮🇷': ['Iran ', ' Iranian flag'],
  '👨‍🍳': ['cook ', ' chef ', ' baker ', ' sous chef ', ' man cook ', ' man chef ', ' man baker ', ' man sous chef'],
  '😓': ['sweat ', ' tired ', ' sweating ', ' hard work ', ' work hard ', ' working hard'],
  '🤒': [
    'sick ',
    ' thermometer ',
    ' fever ',
    ' temperature ',
    ' flu ',
    ' high fever ',
    ' high temperature ',
    ' ill ',
    ' illin ',
    ' face with thermometer ',
    ' unwell ',
    ' not well',
  ],
  '🌔': ['moon'],
  // '🇨🇻': ['Cape Verde ', ' Cape Verdean flag'],
  '💺': ['seat ', ' seats'],
  '🤓': [
    'nerd ',
    ' geek ',
    ' nerd face ',
    ' nerdy ',
    ' geeky ',
    ' book smart ',
    ' wearing glasses ',
    ' wear glasses ',
    ' take glasses ',
    ' four eyes ',
    ' intelligent ',
    ' professor ',
    ' teacher’s pet',
  ],
  '😔': [
    'sad ',
    ' hurt ',
    ' sad emoji ',
    ' sad face ',
    ' sullen ',
    ' oh well ',
    ' sigh ',
    ' disappointed ',
    ' lonely ',
    ' feel bad ',
    ' downcast ',
    ' long face ',
    ' somber ',
    ' solemn ',
    ' melancholy ',
    ' dejected ',
    ' glum ',
    ' gloomy ',
    ' heartbroken ',
    ' dreary ',
    ' unhappy ',
    ' sorrowful ',
    ' bummed out ',
    ' long-faced',
  ],
  '🌕': ['full moon ', ' moon'],
  '💻': [
    'laptop ',
    ' MacBook ',
    ' MacBook Pro ',
    ' MacBook Air ',
    ' computer ',
    ' laptops ',
    ' MacBooks ',
    ' MacBook Pros ',
    ' MacBook Airs ',
    ' computers ',
    ' Mac',
  ],
  '💼': ['briefcase ', ' portfolio ', ' bag ', ' briefcases ', ' portfolios ', ' bags'],
  '🤔': [
    'hmm ',
    ' thinking ',
    ' think ',
    ' let me think ',
    ' I don’t know ',
    ' not sure ',
    ' pensive ',
    ' I’ll get back to you ',
    ' let me get back to you ',
    ' I’ll let you know ',
    ' perplexed ',
    ' pondering ',
    ' ponder ',
    ' stumped ',
    ' contemplative ',
    ' contemplate ',
    ' speculating ',
    ' evaluating ',
    ' puzzling',
  ],
  '😕': [
    'confused ',
    ' bothered ',
    ' perplexed ',
    ' defeated ',
    ' indifferent ',
    ' puzzled ',
    ' disorganized ',
    ' discombobulated ',
    ' baffled ',
    ' bewildered ',
    ' hesitant ',
    ' unnerved',
  ],
  '🌖': ['moon'],
  '☀️': ['sun ', ' sunshine ', ' sunny'],
  '😖': ['tortured ', ' painful ', ' excruciating ', ' ache ', ' achy ', ' achey ', ' miserable'],
  '🤕': [
    'sick ',
    ' headache ',
    ' bandage ',
    ' bumped my head ',
    ' bumped your head ',
    ' bumped his head ',
    ' bumped her head ',
    ' hurt ',
    ' beat up ',
    ' face with bandage ',
    ' face with head bandage ',
    ' injured',
  ],
  '🌗': ['moon'],
  // '🇮🇸': ['Iceland ', ' Icelandic flag'],
  '🚴‍♂️': [
    'cyclist ',
    ' bicyclist ',
    ' cycling ',
    ' biking ',
    ' biker ',
    ' bikers ',
    ' road bike ',
    ' cyclists ',
    ' bicyclists ',
    ' man biking',
  ],
  '😗': ['whistling ', ' kissing face ', ' kissy face ', ' kiss face ', ' duck face'],
  '🤖': ['robot ', ' robots'],
  '🌘': ['moon'],
  // '🇨🇼': ['Curaçao ', ' Curacao ', ' Curaçaoan flag'],
  '⭕️': ['circle'],
  '😘': [
    'kiss ',
    ' blow a kiss ',
    ' kissy face ',
    ' kiss face ',
    ' kissing smiley ',
    ' kissing emoji ',
    ' kisses ',
    ' XO ',
    ' XX ',
    ' XOXO ',
    ' kiss you ',
    ' love you ',
    ' I love you ',
    ' missing you ',
    ' miss you ',
    ' smooch',
  ],
  '🤗': [
    'hug ',
    ' my bad ',
    ' hugs ',
    ' tickles ',
    ' hugging ',
    ' hugging face ',
    ' hug face ',
    ' huggy ',
    ' touchy-feely ',
    ' affectionate ',
    ' jazz hands',
  ],
  '🌙': ['crescent ', ' moon ', ' crescent moon'],
  '👨‍🎨': [
    'artist ',
    ' artisan ',
    ' painter ',
    ' artiste ',
    ' designer ',
    ' creative designer ',
    ' man artist ',
    ' man artisan ',
    ' man painter ',
    ' man artiste ',
    ' man creative designer',
  ],
  '📀': ['DVD ', ' DVDs'],
  '😙': ['kiss ', ' kissing face ', ' whistling ', ' kissy face ', ' kiss face ', ' duck face'],
  '🧖‍♀️': ['woman in sauna ', ' sauna ', ' steam room'],
  // '🇱🇷': ['Liberia ', ' Liberian flag'],
  '🤘': ['sign of the horns ', ' rock on ', ' heavy metal'],
  '🌚': ['moon'],
  '😚': [
    'kiss ',
    ' kiss face ',
    ' kissy face ',
    ' smooch ',
    ' kisses ',
    ' smooches ',
    ' XO ',
    ' XX ',
    ' XOXO ',
    ' kiss you ',
    ' kissing face ',
    ' duck face',
  ],
  '🌛': ['moon'],
  '🤙': [
    'call me ',
    ' shaka sign ',
    ' shaka ',
    ' hang loose ',
    ' hang ten ',
    ' hand with thumb and pinky ',
    ' hit me up',
  ],
  // '🇮🇹': ['Italy ', ' Italian flag'],
  // '🇨🇽': ['Christmas Island ', ' Christmas Island flag'],
  '😛': [
    'silly ',
    ' tongue ',
    ' sticking my tongue out ',
    ' tongue out emoji ',
    ' tongue out face ',
    ' tongue out smiley',
  ],
  '🌜': ['moon'],
  '🤚': ['hand ', ' back hand ', ' back of hand'],
  '😜': [
    'crazy ',
    ' silly ',
    ' hehe ',
    ' hee hee ',
    ' teehee ',
    ' cray ',
    ' wild ',
    ' excited ',
    ' loco ',
    ' sticking my tongue out ',
    ' tongue out emoji ',
    ' tongue out face ',
    ' tongue out smiley',
  ],
  '🌝': ['moon'],
  '🤛': ['fist ', ' punch ', ' left punch ', ' left-facing punch'],
  // '🇷🇴': ['Romania ', ' Romanian flag'],
  // '🇱🇸': ['Lesotho ', ' Basotho flag'],
  '😝': [
    'crazy ',
    ' lol ',
    ' laughing ',
    ' lolz ',
    ' lols ',
    ' lulz ',
    ' rotfl ',
    ' rotflmao ',
    ' excited ',
    ' silly ',
    ' loco ',
    ' sticking my tongue out ',
    ' tongue out emoji ',
    ' tongue out face ',
    ' tongue out smiley',
  ],
  '🌞': ['sunshine ', ' sunny ', ' sun'],
  '🤜': ['fist ', ' punch ', ' right punch ', ' right-facing punch'],
  // '🇨🇾': ['Cyprus ', ' Cypriot flag'],
  '😞': [
    'sad ',
    ' hurt ',
    ' sad emoji ',
    ' sad face ',
    ' disappointed ',
    ' so sad ',
    ' embarrassed ',
    ' frown face ',
    ' frowny face ',
    ' lonely ',
    ' feel bad ',
    ' bummed out ',
    ' downcast ',
    ' long face ',
    ' dejected ',
    ' gloomy ',
    ' heartbroken ',
    ' dreary ',
    ' long-faced ',
    ' unhappy ',
    ' sorrowful',
  ],
  '🌟': [
    'star ',
    ' shining star ',
    ' bright star ',
    ' twinkling star ',
    ' stars ',
    ' bright stars ',
    ' twinkling stars',
  ],
  '🤝': [
    'handshake ',
    ' two hands in handshake ',
    ' two hands shaking ',
    ' make a deal ',
    ' making a deal ',
    ' seal the deal',
  ],
  '📆': ['calendar ', ' calendars'],
  // '🇽🇰': ['Kosovo ', ' Kosovar flag'],
  '😟': [
    'worried ',
    ' anxious ',
    ' afraid ',
    ' concerned ',
    ' scared ',
    ' uneasy ',
    ' nervous ',
    ' scare me ',
    ' scares me ',
    ' insecure ',
    ' troubled ',
    ' distressed ',
    ' dreading ',
    ' hesitant',
  ],
  '🌠': ['shooting star ', ' shooting stars'],
  '🤞': [
    'crossed ',
    ' fingers crossed ',
    ' hand with fingers crossed ',
    ' index and middle finger crossed ',
    ' i hope ',
    ' here’s hoping',
  ],
  '👩‍🔬': [
    'scientist ',
    ' chemist ',
    ' physicist ',
    ' lab technician ',
    ' rocket scientist ',
    ' woman scientist ',
    ' woman chemist ',
    ' woman physicist ',
    ' woman lab technician ',
    ' woman rocket scientist',
  ],
  '😠': [
    'angry ',
    ' mad ',
    ' pissed ',
    ' mad face ',
    ' angry face ',
    ' grumpy face ',
    ' upset ',
    ' surly ',
    ' agitated ',
    ' annoyed ',
    ' irritated ',
    ' irritating ',
    ' pissed off ',
    ' irritable',
  ],
  // '🇱🇹': ['Lithuania ', ' Lithuanian flag'],
  '🌡': ['thermometer ', ' thermometers'],
  '🤟': ['I love you ', ' gesture ', ' sign language ', ' ILY'],
  // '🇨🇿': ['Czech Republic ', ' Czech flag ', ' Czechia ', ' Czechia flag'],
  '😡': [
    'angry ',
    ' mad ',
    ' upset ',
    ' pissed ',
    ' angry face ',
    ' mad face ',
    ' steaming red ',
    ' road rage ',
    ' grumpy face ',
    ' grumpy ',
    ' surly ',
    ' agitated ',
    ' annoyed ',
    ' pissed off ',
    ' irritable',
  ],
  '🤠': ['cowboy ', ' cowboy hat ', ' face with hat ', ' face with cowboy hat'],
  '👨‍⚕️': [
    'health worker ',
    ' hospital worker ',
    ' nurse ',
    ' doctor ',
    ' physician ',
    ' chiropractor ',
    ' surgeon ',
    ' man health worker ',
    ' man hospital worker ',
    ' man doctor ',
    ' man physician ',
    ' man chiropractor ',
    ' man surgeon',
  ],
  '😢': [
    'sad ',
    ' hurt ',
    ' cry ',
    ' tearful ',
    ' sad emoji ',
    ' sad face ',
    ' single tear ',
    ' disappointed ',
    ' lonely ',
    ' feel bad ',
    ' crying ',
    ' upset',
  ],
  '🤡': ['clown ', ' clowns ', ' clown face'],
  '📊': ['bar chart ', ' bar charts'],
  '😣': ['painful ', ' uncomfortable ', ' agitated ', ' irritated'],
  '🙆‍♂️': ['ok gesture ', ' hands on head ', ' stretching'],
  '🌤': ['partly cloudy'],
  // '🇱🇺': ['Luxembourg ', ' Luxembourg flag ', ' Luxembourgish flag'],
  '🤢': [
    'green face ',
    ' sick face ',
    ' nauseated face ',
    ' sick ',
    ' nauseated ',
    ' puke ',
    ' puking ',
    ' pukes ',
    ' puked ',
    ' vomit ',
    ' feeling sick ',
    ' going to be sick ',
    ' throw up ',
    ' barf ',
    ' barfing ',
    ' poisoned ',
    ' yuck ',
    ' nasty',
  ],
  '😤': [
    'fuming ',
    ' pissed ',
    ' argh ',
    ' pissed off ',
    ' angry ',
    ' raging ',
    ' perturbed ',
    ' seething ',
    ' with rage ',
    ' hmph ',
    ' irritated',
  ],
  '🌥': ['mostly cloudy'],
  '🤣': [
    'rofl ',
    ' laughing face ',
    ' rolling on the floor laughing face ',
    ' happy crying ',
    ' happy tears ',
    ' so funny ',
    ' too funny ',
    ' hilarious ',
    ' lol ',
    ' cracking up ',
    ' cracked up ',
    ' crack me up ',
    ' dying laughing ',
    ' tears of joy ',
    ' tears of happiness ',
    ' funny ',
    ' funniest ',
    ' laughing ',
    ' haha ',
    ' hehe ',
    ' crying smiley ',
    ' lmao ',
    ' lolz ',
    ' lols ',
    ' lulz ',
    ' rotfl ',
    ' rotflmao ',
    ' roflmao',
  ],
  '📌': ['pushpin ', ' pushpins'],
  '🌦': ['sunshower'],
  '🤤': ['delicious ', ' yummy ', ' nom nom ', ' nomnom ', ' drool ', ' drooling ', ' sleepy'],
  '😦': [
    'worried ',
    ' stunned ',
    ' anxious ',
    ' afraid ',
    ' concerned ',
    ' scared ',
    ' uneasy ',
    ' disturbed ',
    ' astonished ',
    ' appalled ',
    ' alarmed ',
    ' spooked',
  ],
  '🌧': ['rain ', ' raining'],
  '🤥': ['lying ', ' pinocchio ', ' lied ', ' liar ', ' long nose face ', ' long nose'],
  // '🇱🇻': ['Latvia ', ' Latvian flag'],
  '😧': [
    'worried ',
    ' stunned ',
    ' anxious ',
    ' afraid ',
    ' concerned ',
    ' scared ',
    ' uneasy ',
    ' disturbed ',
    ' astonished ',
    ' appalled ',
    ' alarmed ',
    ' spooked ',
    ' anguished ',
    ' fearful',
  ],
  '🌨': ['snow storm ', ' blizzard ', ' snowing'],
  '🏋️‍♂️': [
    'weightlifting ',
    ' weight lifting ',
    ' weight lifter ',
    ' weightlifter ',
    ' clean and jerk ',
    ' lift weights ',
    ' lifting weights ',
    ' working out ',
    ' work out ',
    ' man lifting weights',
  ],
  '🌩': ['lightning ', ' thunderstorm ', ' thunderstorms ', ' thunder storm ', ' thunder storms'],
  '🤧': [
    'sick ',
    ' flu ',
    ' ill ',
    ' face with tissue ',
    ' unwell ',
    ' not well ',
    ' face with kleenex ',
    ' face with handkerchief ',
    ' face with a cold ',
    ' blowing nose ',
    ' sneeze ',
    ' sneezing ',
    ' sneezed ',
    ' gesundheit ',
    ' salud ',
    ' have a cold',
  ],
  '😩': [
    'stressed ',
    ' worried ',
    ' distraught ',
    ' distressed ',
    ' anxious ',
    ' tormented ',
    ' apprehensive ',
    ' flustered ',
    ' neglected ',
    ' lonely ',
    ' dismayed ',
    ' hopeless ',
    ' miserable ',
    ' dejected ',
    ' despair ',
    ' despairing ',
    ' embarrassed ',
    ' exhausted ',
    ' hysterical ',
    ' fussy',
  ],
  '🌪': ['tornado ', ' tornados ', ' tornadoes ', ' twister ', ' twisters'],
  '🤨': [
    'face with raised eyebrow ',
    ' raised eyebrow ',
    ' skeptic ',
    ' skeptical ',
    ' Colbert ',
    ' quizzical ',
    ' people’s eyebrow',
  ],
  '⛹️‍♀️': ['basketball player ', ' basketball players ', ' baller ', ' ballers ', ' woman playing basketball'],
  '🤩': ['starry eyed ', ' starry-eyed ', ' star eyes ', ' star-struck ', ' star struck ', ' starry eyes ', ' stars'],
  // '🇷🇸': ['Serbia ', ' Serbian flag'],
  '😫': [
    'stressed ',
    ' worried ',
    ' distraught ',
    ' flustered ',
    ' whiny ',
    ' distressed ',
    ' anxious ',
    ' tormented ',
    ' apprehensive',
  ],
  '🤪': ['goofy face ', ' zany face ', ' silly face ', ' funny face'],
  '⌨️': ['keyboard'],
  '📓': ['notebook ', ' journal ', ' notebooks'],
  '😬': [
    'braces ',
    ' tense ',
    ' nervous ',
    ' oops ',
    ' eek ',
    ' gnashing teeth ',
    ' jittery ',
    ' whoops ',
    ' restless ',
    ' uneasy ',
    ' apprehensive ',
    ' fidgety ',
    ' agitated ',
    ' unnerved',
  ],
  '🌭': ['hot dog ', ' hot dogs'],
  '🤫': ['shush ', ' hush ', ' shushing ', ' hushing ', ' quiet ', ' shhh'],
  '😭': [
    'tears ',
    ' sad ',
    ' hurt ',
    ' cry ',
    ' sad emoji ',
    ' sad face ',
    ' butt hurt ',
    ' cry baby ',
    ' cry babies ',
    ' upset ',
    ' lonely ',
    ' emotional ',
    ' so sad ',
    ' so upset ',
    ' so lonely ',
    ' so hurt ',
    ' despondent ',
    ' heartbroken ',
    ' sobbing ',
    ' wailing ',
    ' crying ',
    ' miserable ',
    ' bawling ',
    ' hysterical ',
    ' fussy ',
    ' distraught',
  ],
  '🌮': ['taco ', ' tacos'],
  '🤾‍♂️': ['handball ', ' playing handball ', ' man playing handball ', ' handball player'],
  '🤬': [
    'bleeped ',
    ' face with symbols ',
    ' symbols over mouth ',
    ' cursing ',
    ' swearing ',
    ' cussing ',
    ' censored',
  ],
  '🏊‍♀️': ['pool ', ' swimmer ', ' swimming ', ' swimmers ', ' woman swimming'],
  '♦️': ['cards ', ' diamond ', ' diamonds'],
  '😮': [
    'shocked ',
    ' omg ',
    ' wow ',
    ' ohh ',
    ' ohhh ',
    ' whoa ',
    ' whut ',
    ' astonished ',
    ' baffled ',
    ' surprised ',
    ' appalled ',
    ' astounded ',
    ' flabbergasted ',
    ' startled ',
    ' taken aback ',
    ' ooh ',
    ' oooh',
  ],
  '🌯': ['burrito ', ' burritos'],
  '📖': ['book ', ' study ', ' reading ', ' books'],
  '⚡️': ['spark ', ' electric ', ' zap ', ' sparks ', ' zaps'],
  '🤭': ['hand over mouth ', ' laughing ', ' giggling ', ' laugh ', ' giggle'],
  '😯': [
    'shocked ',
    ' surprised ',
    ' omg ',
    ' wow ',
    ' ohh ',
    ' ohhh ',
    ' whoa ',
    ' whut ',
    ' baffled ',
    ' astonished ',
    ' appalled ',
    ' astounded ',
    ' flabbergasted ',
    ' startled ',
    ' taken aback ',
    ' ooh ',
    ' oooh',
  ],
  '🌰': ['chestnut ', ' chestnuts'],
  '🤮': [
    'vomit ',
    ' vomiting ',
    ' vomited ',
    ' vomits ',
    ' puke ',
    ' puking ',
    ' puked ',
    ' pukes ',
    ' sick ',
    ' upchuck ',
    ' barf ',
    ' barfed ',
    ' barfing ',
    ' barfs',
  ],
  '🌱': ['seedling ', ' plants ', ' seedlings ', ' vegan ', ' vegetarian'],
  '🤯': ['exploding head ', ' mind blown ', ' head exploding ', ' shocked'],
  '😱': [
    'surprised ',
    ' worried ',
    ' scared ',
    ' concerned ',
    ' spooked ',
    ' afraid ',
    ' oh no ',
    ' alarmed ',
    ' panicky ',
    ' startled ',
    ' scares me ',
    ' I’m shocked',
  ],
  // '🇺🇸': ['United States ', ' USA ', ' American flag ', ' United States of America ', ' US flag'],
  // '🇷🇺': ['Russia ', ' Russian flag'],
  // '🇱🇾': ['Libya ', ' Libyan flag'],
  '🌲': ['tree ', ' evergreen ', ' pine ', ' fir ', ' trees ', ' evergreens ', ' pine tree ', ' firs'],
  '🤰': [
    'pregnant ',
    ' pregnant woman ',
    ' woman with child ',
    ' pregnancy ',
    ' having a baby ',
    ' giving birth ',
    ' pregnant lady',
  ],
  '😲': [
    'astonished ',
    ' shocked ',
    ' surprised ',
    ' omg ',
    ' wow ',
    ' ohh ',
    ' ohhh ',
    ' whoa ',
    ' whut ',
    ' baffled ',
    ' appalled ',
    ' astounded ',
    ' flabbergasted ',
    ' startled ',
    ' taken aback ',
    ' ooh ',
    ' oooh',
  ],
  '🌳': ['tree ', ' elm ', ' aspen ', ' birch ', ' forest ', ' trees ', ' elms ', ' aspens ', ' birches ', ' forests'],
  '📚': ['books ', ' textbooks ', ' library ', ' homework ', ' book ', ' textbook'],
  '🤱': [
    'breast feeding ',
    ' breast-feeding ',
    ' breastfeeding ',
    ' breastfeed ',
    ' breast-feed ',
    ' breastfed ',
    ' breast-fed ',
    ' nursing',
  ],
  '😳': [
    'surprised ',
    ' worried ',
    ' shocked ',
    ' embarrassed ',
    ' wow ',
    ' seriously ',
    ' for real ',
    ' alarmed ',
    ' concerned ',
    ' so wired ',
    ' scared ',
    ' spooked ',
    ' afraid ',
    ' uneasy ',
    ' disturbed ',
    ' scare me ',
    ' scares me ',
    ' bewildered ',
    ' stunned ',
    ' astonished ',
    ' appalled ',
    ' astounded',
  ],
  '🌴': [
    'tropical ',
    ' coconut ',
    ' date tree ',
    ' palm tree ',
    ' island ',
    ' coconut tree ',
    ' coconuts ',
    ' islands ',
    ' coconut trees ',
    ' date trees ',
    ' palm trees',
  ],
  '🤲': ['hands held out ', ' open hands ', ' open palms ', ' palms up together ', ' cupped hands'],
  '😴': [
    'sleepy ',
    ' sleeping ',
    ' tired ',
    ' napping ',
    ' sleepy face ',
    ' sleeping face ',
    ' nap ',
    ' sleep ',
    ' snoring ',
    ' nap time ',
    ' asleep ',
    ' exhausted ',
    ' zzz ',
    ' Zs',
  ],
  '🌵': ['cactus ', ' desert ', ' cactuses ', ' cacti ', ' deserts'],
  '💆‍♀️': ['massage ', ' massages ', ' woman massage'],
  '🤳': ['selfie ', ' taking a selfie ', ' taking a photo ', ' taking a pic ', ' camera phone ', ' taking a picture'],
  '👨‍✈️': [
    'pilot ',
    ' aviator ',
    ' captain ',
    ' flight attendant ',
    ' navigator ',
    ' man pilot ',
    ' man aviator ',
    ' man captain ',
    ' man flight attendant ',
    ' man navigator ',
    ' steward',
  ],
  '😵': [
    'dizzy ',
    ' dizzy face ',
    ' cross eyes ',
    ' cross eyed ',
    ' passed out ',
    ' I’m dying ',
    ' I’m dead ',
    ' drunk ',
    ' intoxicated ',
    ' hungover ',
    ' hung over ',
    ' x eyes ',
    ' x eyed',
  ],
  '🌶': ['chili ', ' spicy ', ' chilies ', ' peppers ', ' vegetable ', ' vegetables ', ' veggies'],
  '🤴': ['prince ', ' boy with crown ', ' crown ', ' man with crown ', ' king'],
  '📝': ['memo ', ' notes ', ' paper ', ' note ', ' memos ', ' notepad ', ' notepads'],
  '😶': [
    'speechless ',
    ' no words ',
    ' whut ',
    ' stunned ',
    ' flummoxed ',
    ' gobsmacked ',
    ' blankly ',
    ' vacant expression ',
    ' blank expression ',
    ' face with no mouth',
  ],
  '🌷': ['tulip ', ' flower ', ' tulips ', ' flowers'],
  '🤵': ['tuxedo ', ' man in tuxedo ', ' person in tuxedo ', ' formal attire ', ' groom ', ' bridegroom'],
  '📞': ['telephone ', ' handset ', ' phone ', ' landline ', ' telephones ', ' handsets ', ' phones ', ' landlines'],
  '😷': [
    'sick ',
    ' mask ',
    ' flu ',
    ' stinks ',
    ' nasty ',
    ' SARS ',
    ' epidemic ',
    ' epidemics ',
    ' ill ',
    ' contagious ',
    ' contagion ',
    ' outbreak ',
    ' outbreaks ',
    ' illin ',
    ' face mask ',
    ' sick mask ',
    ' medical mask ',
    ' face with medical mask ',
    ' surgeon ',
    ' eww ',
    ' bad breath',
  ],
  '🌸': ['cherry blossom ', ' cherry blossoms'],
  '🤶': ['Claus ', ' Mrs. Claus ', ' Mother Christmas'],
  '🤷‍♂️': [
    'shrug ',
    ' shrugging ',
    ' man shrugging ',
    ' confused man ',
    ' confused ',
    ' undecided ',
    ' indecisive ',
    ' I don’t know ',
    ' i dunno ',
    ' dunno ',
    ' shrugged ',
    ' shruggie ',
    ' don’t care ',
    ' I don’t care',
  ],
  '🏃‍♀️': ['runner ', ' jogger ', ' jogging ', ' run ', ' running ', ' runners ', ' woman running'],
  // '🇷🇼': ['Rwanda ', ' Rwandan flag'],
  '🌹': ['rose ', ' flower ', ' red rose ', ' roses ', ' flowers ', ' red roses'],
  '🌺': ['azalea ', ' flower ', ' Hawaiian ', ' pua aloalo ', ' hibiscus ', ' azaleas ', ' flowers ', ' hibiscuses'],
  '🌻': ['sunflower ', ' sunflowers'],
  '🧞‍♂️': ['genie ', ' man genie ', ' djinn'],
  '📢': ['megaphone ', ' loudspeaker ', ' bullhorn ', ' megaphones ', ' loudspeakers ', ' bullhorns'],
  '🌼': ['flower ', ' daffodil ', ' flowers ', ' daffodils'],
  '🤺': ['fencer ', ' fencers ', ' fencing ', ' duel ', ' dueling ', ' sword fighting ', ' sword fight'],
  '✏️': ['pencil ', ' eraser ', ' pencils ', ' erasers'],
  '📣': ['megaphone ', ' megaphones ', ' cheerleader ', ' cheerleaders'],
  // '🇧🇦': [
  //   'Bosnia & Herzegovina ',
  //   ' Bosnia and Herzegovina ',
  //   ' Bosnia ',
  //   ' Herzegovina ',
  //   ' Bosnian flag ',
  //   ' Herzegovinian flag',
  // ],
  '🌽': ['corn ', ' ear of corn ', ' vegetable ', ' vegetables ', ' veggies'],
  '🕵️‍♂️': ['spy ', ' spying ', ' sleuth ', ' sleuthing ', ' Sherlock ', ' Sherlock Holmes'],
  '🌾': ['corn ', ' wheat'],
  '🌿': ['basil ', ' oregano ', ' herbs ', ' herb'],
  '📦': ['package ', ' box ', ' shipment ', ' delivery ', ' packages ', ' boxes ', ' shipments ', ' deliveries'],
  '🍀': ['lucky clover ', ' lucky ', ' four leaf clover ', ' four leaf clovers ', ' lucky clovers ', ' leprechaun'],
  // // // '🇧🇧': ['Barbados ', ' Barbadian flag'],
  '🍁': ['maple ', ' leaf ', ' leaves ', ' maple leaf ', ' maple leaves'],
  '🙁': [
    'sad ',
    ' bummed ',
    ' hurt ',
    ' frown face ',
    ' frowny face ',
    ' sad emoji ',
    ' sad face ',
    ' disappointed ',
    ' lonely ',
    ' feel bad ',
    ' downcast ',
    ' long face ',
    ' somber ',
    ' solemn ',
    ' melancholy ',
    ' dejected ',
    ' glum ',
    ' gloomy ',
    ' dreary ',
    ' unhappy ',
    ' sorrowful ',
    ' bummed out',
  ],
  '🍂': ['autumn ', ' leaf'],
  '🥀': [
    'rose ',
    ' roses ',
    ' flower ',
    ' flowers ',
    ' dying flower ',
    ' dying rose ',
    ' wilting ',
    ' wilted ',
    ' wilted flower ',
    ' wilted rose ',
    ' red rose',
  ],
  '🙂': ['happy ', ' smiley face ', ' smiley emoji ', ' that’s nice ', ' in a good mood ', ' I’m ok ', ' I’m fine'],
  '🍃': ['leaf ', ' two leaves'],
  '🥁': ['drum ', ' snare drum ', ' drumsticks ', ' drum with drumsticks ', ' musical instrument'],
  '🙃': [
    'silly ',
    ' happy ',
    ' upside down happy face ',
    ' silly face ',
    ' happy face ',
    ' upside down face ',
    ' joking ',
    ' goofy ',
    ' hehe',
  ],
  '🍄': ['mushroom ', ' mushrooms'],
  '🥂': [
    'champagne glasses ',
    ' champagne ',
    ' a toast ',
    ' celebratory toast ',
    ' cheers ',
    ' toasts ',
    ' clinking glasses ',
    ' two glasses ',
    ' champagne flutes',
  ],
  '🙄': [
    'duh ',
    ' uhh ',
    ' rolling eyes ',
    ' eye roll ',
    ' rolling eye face ',
    ' face with rolling eyes ',
    ' oh please ',
    ' donk ',
    ' obviously',
  ],
  '🍅': ['tomato ', ' tomatoes ', ' tomatos ', ' vegetable ', ' vegetables ', ' veggies'],
  '🥃': [
    'tumbler glass ',
    ' a glass ',
    ' a drink ',
    ' whisky ',
    ' whiskey ',
    ' bourbon ',
    ' lowball glass ',
    ' glass of whisky ',
    ' glass of whiskey ',
    ' glass of bourbon',
  ],
  '🧚‍♀️': ['woman fairy ', ' woman fairies ', ' fairy ', ' fairies ', ' pixie ', ' pixies'],
  '🧗‍♂️': ['climber ', ' climbing ', ' rock climbing ', ' rock climber ', ' man climber ', ' man climbing'],
  '🍆': ['eggplant ', ' eggplants ', ' vegetable ', ' vegetables ', ' veggies'],
  '🥄': ['spoon ', ' spoons ', ' utensil ', ' utensils ', ' silverware'],
  // // // '🇺🇾': ['Uruguay ', ' Uruguayan flag'],
  // // // '🇧🇩': ['Bangladesh ', ' Bangladeshi flag'],
  '🍇': ['grapes ', ' fruit ', ' grape ', ' fruits'],
  '🥅': ['goal ', ' goal net ', ' soccer'],
  '📮': ['postbox ', ' mailbox'],
  '🍈': ['honeydew ', ' cantaloupe ', ' melon ', ' fruit ', ' honeydews ', ' cantaloupes ', ' melons ', ' fruits'],
  '🙈': ['stop seeing ', ' oh no'],
  '🍉': ['fruit ', ' watermelon ', ' melon ', ' fruits ', ' watermelons ', ' melons'],
  '🥇': ['medal ', ' medals ', ' first place ', ' gold medal ', ' first place gold medal ', ' award'],
  // // // '🇺🇿': ['Uzbekistan ', ' Uzbek flag'],
  '🙉': ['stop listening ', ' oh no'],
  // // // '🇪🇨': ['Ecuador ', ' Ecuadorean flag'],
  '📱': [
    'cellphone ',
    ' cellphones ',
    ' mobile phone ',
    ' mobile phones ',
    ' iPhone ',
    ' iPod ',
    ' phone ',
    ' iPhones ',
    ' iPods ',
    ' phones',
  ],
  // // // '🇧🇪': ['Belgium ', ' Belgian flag'],
  '🍊': ['orange ', ' tangerine ', ' fruit ', ' citrus ', ' oranges ', ' tangerines ', ' fruits'],
  '🥈': ['medal ', ' second place ', ' silver medal ', ' second place silver medal ', ' award'],
  '🙊': ['stop talking ', ' oh no ', ' oops'],
  '📲': ['phone ', ' iPhone ', ' phones ', ' iPhones'],
  '🍋': ['lemon ', ' fruit ', ' lemons ', ' fruits'],
  '🥉': ['medal ', ' third place ', ' bronze medal ', ' third place bronze medal ', ' award'],
  '🍌': ['banana ', ' fruit ', ' bananas ', ' fruits'],
  '🥊': ['boxing glove ', ' red boxing glove ', ' boxing ', ' punch ', ' glove'],
  '📳': ['vibration mode'],
  '🙌': ['woohoo ', ' wohoo ', ' yay ', ' raise the roof ', ' woop ', ' hands in the air ', ' high five'],
  '🚴‍♀️': [
    'cyclist ',
    ' bicyclist ',
    ' cycling ',
    ' biking ',
    ' biker ',
    ' bikers ',
    ' cyclists ',
    ' road bike ',
    ' bicyclists ',
    ' woman biking',
  ],
  '🍍': ['pineapple ', ' fruit ', ' pineapples ', ' fruits'],
  '🥋': [
    'uniform ',
    ' martial art ',
    ' martial arts ',
    ' martial arts uniform ',
    ' karate uniform ',
    ' karate ',
    ' judo uniform ',
    ' tae kwon do uniform ',
    ' karate gi ',
    ' tae kwon do ',
    ' judo ',
    ' hiyaa ',
    ' black belt ',
    ' karate chop ',
    ' kung fu ',
    ' taekwondo',
  ],
  // // // '🇧🇫': ['Burkina Faso ', ' Burkinabe flag'],
  '🍎': ['apple ', ' fruit ', ' apples ', ' fruits ', ' red apple'],
  '🥌': ['curling ', ' curling stone ', ' curling stones'],
  '🍏': ['apple ', ' fruit ', ' fruits ', ' apples ', ' green apple'],
  '📶': ['signal strength symbol'],
  '🙏': [
    'amen ',
    ' pretty please ',
    ' prayer ',
    ' namaste ',
    ' praying ',
    ' thank you ',
    ' thanks ',
    ' gratitude ',
    ' welcome',
  ],
  '🍐': ['pear ', ' fruit ', ' pears ', ' fruits'],
  '📷': ['camera ', ' cameras'],
  '🍑': ['peach ', ' fruit ', ' peaches ', ' fruits'],
  // // // '🇪🇪': ['Estonia ', ' Estonian flag'],
  // // // '🇧🇬': ['Bulgaria ', ' Bulgarian flag'],
  '🍒': ['fruit ', ' cherry ', ' fruits ', ' cherries'],
  '🥐': ['croissant ', ' croissants ', ' butter croissant ', ' butter croissants'],
  '⛄️': ['snow ', ' snowman ', ' snowmen'],
  '🍓': ['fruit ', ' strawberry ', ' fruits ', ' strawberries'],
  '🥑': ['avocado ', ' avocados ', ' half avocado'],
  '📺': ['TV ', ' television ', ' screen'],
  '🍔': ['burger ', ' hamburger ', ' cheeseburger ', ' sliders ', ' burgers ', ' cheeseburgers'],
  '🥒': [
    'cucumber ',
    ' cucumbers ',
    ' sliced cucumber ',
    ' sliced cucumbers ',
    ' vegetable ',
    ' vegetables ',
    ' veggies',
  ],
  '👮‍♂️': [
    'police ',
    ' cop ',
    ' policeman ',
    ' constable ',
    ' police officer ',
    ' officer ',
    ' cops ',
    ' police officers ',
    ' policemen ',
    ' constables ',
    ' officers ',
    ' popo ',
    ' 5-0',
  ],
  '㊙️': ['secret'],
  '📻': ['radio ', ' radios ', ' FM'],
  // // // '🇧🇭': ['Bahrain ', ' Bahraini flag'],
  '🍕': ['pizza ', ' pepperoni ', ' pizza slice ', ' pizzas'],
  '🥓': ['bacon ', ' strips of bacon ', ' two slices of bacon ', ' slice of bacon ', ' slices of bacon'],
  '🍖': ['meat ', ' bone ', ' BBQ'],
  '🥔': ['potato ', ' potatoes ', ' spud ', ' spuds ', ' vegetable ', ' vegetables ', ' veggies'],
  '📽': ['film projector ', ' projector'],
  '🍗': ['chicken ', ' drumstick ', ' BBQ ', ' drumsticks'],
  '🥕': ['carrot ', ' carrots ', ' vegetable ', ' vegetables ', ' veggies'],
  // // // '🇳🇦': ['Namibia ', ' Namibian flag'],
  // // // '🇪🇬': ['Egypt ', ' Egyptian flag'],
  // // // '🇧🇮': ['Burundi ', ' Burundian flag'],
  '🍘': ['rice cracker ', ' rice crackers'],
  '🥖': ['bread ', ' baguette ', ' baguettes ', ' loaf of bread ', ' french bread'],
  '🍙': ['rice ball ', ' rice balls ', ' onigiri'],
  '🥗': ['salad ', ' green salad ', ' lunch ', ' side salad ', ' vegetable ', ' vegetables ', ' veggies'],
  '🙆‍♀️': ['ok gesture ', ' hands on head ', ' stretching'],
  '🍚': ['rice ', ' rice bowl'],
  '🥘': ['pan of food ', ' paella ', ' food ', ' meal ', ' cooking ', ' shallow pan ', ' casserole ', ' dinner'],
  '🍛': ['curry ', ' rice'],
  '🥙': [
    'pita ',
    ' pitas ',
    ' gyro ',
    ' gyros ',
    ' doner kebab ',
    ' falafel ',
    ' stuffed flatbread ',
    ' lunch ',
    ' pita sandwich ',
    ' gyro sandwich ',
    ' kebab sandwich ',
    ' falafel sandwich',
  ],
  // // // '🇪🇭': ['Western Sahara ', ' Sahrawi flag'],
  // // // '🇧🇯': ['Benin ', ' Beninese flag'],
  '🍜': ['soup ', ' noodle ', ' ramen ', ' soba ', ' udon'],
  '🥚': ['egg ', ' eggs'],
  '🍝': ['noodles ', ' pasta ', ' spaghetti'],
  '🥛': ['milk ', ' glass of milk ', ' dairy'],
  '🍞': ['bread'],
  '🥜': ['peanuts ', ' nut ', ' nuts ', ' peanut'],
  // // // '🇶🇦': ['Qatar ', ' Qatari flag'],
  // // // '🇳🇨': ['New Caledonia ', ' New Caledonian flag'],
  // // // '🇰🇪': ['Kenya ', ' Kenyan flag'],
  '🍟': ['fries ', ' french fries ', ' french fry'],
  '👩‍🎤': [
    'singer ',
    ' musician ',
    ' artist ',
    ' musical artist ',
    ' woman singer ',
    ' woman musician ',
    ' woman artist ',
    ' woman musical artist ',
    ' diva ',
    ' vocalist ',
    ' minstrel ',
    ' soloist',
  ],
  '🥝': ['kiwi ', ' fruit ', ' kiwi fruit ', ' green fruit ', ' half kiwi ', ' kiwis ', ' fruits'],
  '🍠': ['sweet potato ', ' sweet potatoes ', ' vegetable ', ' vegetables ', ' veggies ', ' yam ', ' yams'],
  '🥞': [
    'pancake ',
    ' flapjack ',
    ' flapjacks ',
    ' short stack ',
    ' pancakes ',
    ' stack of pancakes ',
    ' hotcakes ',
    ' breakfast ',
    ' breakfast food',
  ],
  '💇‍♂️': ['haircut ', ' salon ', ' haircuts ', ' man haircut'],
  '🍡': ['dango'],
  '🥟': ['dumpling ', ' dumplings ', ' potsticker ', ' potstickers'],
  '🚣‍♂️': ['rowboat ', ' boat ', ' rowing ', ' rowboats ', ' boats ', ' man rowing ', ' man rowing boat'],
  '🍢': ['oden'],
  // // // '🇧🇱': ['Saint Barthélemy ', ' Saint Barthelemy ', ' Barthélemois flag'],
  '🥠': ['fortune cookie ', ' fortune cookies'],
  '🍣': ['nigiri ', ' maguro ', ' sushi'],
  '🥡': ['takeout box ', ' takeout'],
  '🔊': ['speaker ', ' subwoofer ', ' speakers ', ' subwoofers'],
  '🤾‍♀️': ['handball ', ' playing handball ', ' woman playing handball ', ' handball player'],
  '🏄‍♂️': ['surf ', ' surfing ', ' surfer ', ' surfers ', ' surf’s up ', ' hang ten ', ' man surfing'],
  '🍤': ['shrimp ', ' prawns ', ' scampi ', ' prawn'],
  '🥢': ['chopsticks'],
  '⛳️': ['golf'],
  '🍥': ['fish cake ', ' fish cakes ', ' naruto'],
  '🥣': ['bowl with spoon ', ' soup ', ' porridge ', ' cereal'],
  // // '🇳🇪': ['Niger ', ' Nigerien flag'],
  // // '🇰🇬': ['Kyrgyzstan ', ' Kyrgyzstani flag ', ' Kyrgyz flag'],
  // // '🇧🇲': ['Bermuda ', ' Bermudan flag'],
  '🍦': ['ice cream ', ' icecream ', ' yogurt ', ' soft serve ', ' ice cream cone'],
  '🥤': [
    'cup with straw ',
    ' to-go cup ',
    ' juice ',
    ' juices ',
    ' drink ',
    ' drinks ',
    ' soda ',
    ' sodas ',
    ' soda pop',
  ],
  '🍧': ['gelato ', ' shaved ice ', ' snow cone ', ' snow cones'],
  '🥥': ['coconut ', ' coconuts ', ' fruit'],
  '🍨': ['gelato ', ' ice cream ', ' dessert ', ' desserts'],
  '🥦': ['broccoli'],
  '👩‍⚖️': [
    'judge ',
    ' court room ',
    ' moderator ',
    ' marshal ',
    ' justice of the peace ',
    ' legal official ',
    ' adjudicator ',
    ' judge Judy ',
    ' judicial system ',
    ' justices ',
    ' woman judge',
  ],
  // // '🇳🇫': ['Norfolk Island ', ' Norfolk Island flag'],
  // // '🇰🇭': ['Cambodia ', ' Cambodian flag'],
  // // '🇧🇳': ['Brunei ', ' Bruneian flag'],
  '🔐': ['lock ', ' key ', ' padlock ', ' locks ', ' keys ', ' padlocks'],
  '🍩': ['doughnut ', ' doughnuts ', ' donut ', ' donuts'],
  '🥧': ['pie'],
  '🍪': ['cookie ', ' cookies'],
  '🥨': ['pretzel ', ' pretzels'],
  '🔑': ['key ', ' keys'],
  '🍫': ['chocolate ', ' sweets ', ' chocolates ', ' chocolate bar ', ' chocolate candy'],
  '🥩': ['cut of meat ', ' steak ', ' steaks ', ' ribeye ', ' beef ', ' meat'],
  '🔒': ['lock ', ' padlock ', ' locked ', ' locks ', ' padlocks'],
  '☂': ['umbrella ', ' umbrellas'],
  '🍬': ['sweets ', ' candy ', ' candies'],
  '🥪': ['sandwich ', ' sandwiches'],
  // // '🇹🇨': [
  // //   'Turks & Caicos Islands ',
  // //   ' Turks and Caicos Islands ',
  // //   ' Turks and Caicos ',
  // //   ' Turks and Caicos Island flag',
  // // ],
  // // '🇳🇬': ['Nigeria ', ' Nigerian flag'],
  // // '🇰🇮': ['Kiribati ', ' Kiribati flag'],
  // // '🇭🇰': ['Hong Kong ', ' Hong Kong flag'],
  // // '🇧🇴': ['Bolivia ', ' Bolivian flag'],
  '🍭': ['candy ', ' sweets ', ' lollipop ', ' candies ', ' lollipops'],
  '🔔': ['church bell ', ' church bells'],
  '🥫': ['canned food ', ' tomato can'],
  '🍮': ['flan ', ' dessert ', ' desserts'],
  '🤷‍♀️': [
    'shrug ',
    ' shrugging ',
    ' woman shrugging ',
    ' confused woman ',
    ' confused ',
    ' undecided ',
    ' indecisive ',
    ' I don’t know ',
    ' i dunno ',
    ' dunno ',
    ' shrugged ',
    ' shruggie ',
    ' don’t care ',
    ' I don’t care',
  ],
  '☺️': [
    'you’re welcome ',
    ' you’re very welcome ',
    ' thank you ',
    ' thank you so much ',
    ' that’s nice ',
    ' lucky me ',
    ' I’m lucky ',
    ' blushing ',
    ' shy',
  ],
  '🍯': ['honey'],
  '👩‍🌾': ['farmer ', ' farmer jane ', ' Old Mc’Donald ', ' woman farmer'],
  // '🇹🇩': ['Chad ', ' Chadian flag'],
  '🍰': ['cake ', ' birthday ', ' cakes ', ' birthdays'],
  '👨‍🚀': ['astronaut ', ' cosmonaut ', ' man astronaut'],
  '🧞‍♀️': ['woman genie ', ' djinn ', ' genie ', ' genies'],
  '🧛‍♂️': ['man vampire ', ' man vampires ', ' vampire ', ' vampires ', ' undead ', ' Dracula'],
  '🍱': ['bento ', ' bentos'],
  '🍲': ['soup ', ' pho ', ' noodle ', ' bowl'],
  '🍳': [
    'fried egg ',
    ' frying pan ',
    ' skillet ',
    ' cooking ',
    ' egg ',
    ' breakfast ',
    ' fried eggs ',
    ' eggs ',
    ' breakfasts',
  ],
  // '🇳🇮': ['Nicaragua ', ' Nicaraguan flag'],
  // '🇿🇦': ['South Africa ', ' South African flag'],
  // '🇧🇶': ['Bonaire ', ' Dutch Caribbean flag'],
  '🍴': [
    'lunch ',
    ' dinner ',
    ' fork ',
    ' knife ',
    ' utensil ',
    ' silverware ',
    ' tableware ',
    ' flatware ',
    ' forks ',
    ' knives ',
    ' utensils',
  ],
  '👩‍🍳': [
    'cook ',
    ' chef ',
    ' baker ',
    ' sous chef ',
    ' woman cook ',
    ' woman chef ',
    ' woman baker ',
    ' woman sous chef',
  ],
  '🍵': ['green tea ', ' matcha ', ' tea'],
  '🅾️': ['blood type O'],
  '🍶': ['rice wine ', ' sake bottle ', ' bottle of sake'],
  '⭐️': ['star ', ' stars'],
  // '🇹🇫': ['French Southern Territories ', ' French Southern Territories flag'],
  // '🇭🇳': ['Honduras ', ' Honduran flag'],
  '🍷': ['wine ', ' alcohol ', ' drink ', ' drinks'],
  // '🇧🇷': ['Brazil ', ' Brazilian flag'],
  '🍸': ['martini ', ' cocktail ', ' drink ', ' martinis ', ' cocktails ', ' drinks'],
  '🚵‍♂️': [
    'cyclist ',
    ' bicyclist ',
    ' cycling ',
    ' biking ',
    ' biker ',
    ' bikers ',
    ' cyclists ',
    ' bicyclists ',
    ' mountain bike ',
    ' mountain biking ',
    ' man biking',
  ],
  '🍹': ['cocktail ', ' drink ', ' cocktails ', ' drinks'],
  '🍺': ['beer ', ' pint ', ' alcohol ', ' beers ', ' pints'],
  // '🇹🇬': ['Togo ', ' Togolese flag'],
  // '🇰🇲': ['Comoros ', ' Comoran flag'],
  '👩‍🎨': [
    'artist ',
    ' artisan ',
    ' painter ',
    ' artiste ',
    ' designer ',
    ' creative designer ',
    ' woman artist ',
    ' woman artisan ',
    ' woman painter ',
    ' woman artiste ',
    ' woman creative designer',
  ],
  '👨‍🏫': [
    'teacher ',
    ' teachers ',
    ' professor ',
    ' professors ',
    ' lecturer ',
    ' educator ',
    ' educators ',
    ' schoolteacher ',
    ' schoolteachers ',
    ' prof ',
    ' faculty member ',
    ' faculty members ',
    ' instructor ',
    ' instructors ',
    ' scholar ',
    ' scholars ',
    ' man teacher ',
    ' man teachers ',
    ' man professor ',
    ' man professors ',
    ' man lecturer ',
    ' man educator ',
    ' man educators ',
    ' man schoolteacher ',
    ' man schoolteachers ',
    ' man faculty member',
  ],
  '🍻': ['beer ', ' cheers ', ' pints ', ' beers ', ' pint'],
  '🧗‍♀️': ['climber ', ' climbing ', ' rock climbing ', ' rock climber ', ' woman climber ', ' woman climbing'],
  // '🇧🇸': ['Bahamas ', ' Bahamian flag'],
  '🍼': ['baby ', ' baby bottle ', ' baby bottles ', ' milk bottle ', ' milk bottles'],
  // '🇹🇭': ['Thailand ', ' Thai flag'],
  // '🇳🇱': ['Netherlands ', ' Caribbean Netherlands ', ' Dutch flag'],
  // '🇰🇳': ['Saint Kitts & Nevis ', ' Saint Kitts and Nevis ', ' Saint Kitts flag ', ' Nevis flag'],
  '🍾': ['champagne ', ' celebration'],
  // '🇪🇷': ['Eritrea ', ' Eritrean flag'],
  // '🇧🇹': ['Bhutan ', ' Bhutanese flag'],
  // '🔥': ['bonfire ', ' campfire ', ' flames ', ' fire ', ' bonfires ', ' campfires ', ' flame ', ' fires'],
  // '🇼🇫': ['Wallis & Futuna ', ' Wallis and Futuna ', ' Wallis flag ', ' Futuna flag'],
  '🍿': ['popcorn ', ' movie ', ' buttered popcorn'],
  '🔦': ['flashlight ', ' flashlights'],
  '🎀': ['ribbon ', ' ribbons'],
  '🔧': ['wrench ', ' wrenches'],
  // '🇪🇸': ['Spain ', ' Spanish flag'],
  '🚀': [
    'space ship ',
    ' rocket ',
    ' launch ',
    ' space ships ',
    ' rockets ',
    ' launches ',
    ' spaceship ',
    ' spaceships',
  ],
  '🎁': ['gift ', ' present ', ' bow ', ' birthday ', ' gifts ', ' presents'],
  '🔨': ['hammer ', ' construction'],
  '🦀': ['crab ', ' crabs'],
  '🎂': ['cake ', ' birthday ', ' candles ', ' cakes ', ' birthdays'],
  '🤦‍♂️': [
    'face palm ',
    ' face palming ',
    ' man doing a face palm ',
    ' man face palming ',
    ' hand on face ',
    ' smh ',
    ' SMH ',
    ' oh no ',
    ' don’t tell me ',
    ' say it isn’t so ',
    ' facepalm ',
    ' why did I do that ',
    ' face palm man ',
    ' man face palm',
  ],
  '🔩': ['nut and bolt ', ' nuts and bolts'],
  '🦁': ['lion ', ' lions'],
  '🎃': ['Halloween ', ' pumpkin ', ' jack-o-lantern ', ' pumpkins ', ' jack-o-lanterns'],
  '🚂': ['train ', ' toy train ', ' locomotive ', ' trains ', ' toy trains ', ' locomotives'],
  '👩‍⚕️': [
    'health worker ',
    ' hospital worker ',
    ' nurse ',
    ' doctor ',
    ' physician ',
    ' chiropractor ',
    ' surgeon ',
    ' woman health worker ',
    ' woman hospital worker ',
    ' woman doctor ',
    ' woman physician ',
    ' woman chiropractor ',
    ' woman surgeon',
  ],
  '🦂': ['scorpion ', ' scorpions'],
  '🎄': ['Christmas tree ', ' Christmas ', ' Christmas trees'],
  '🚃': ['railway ', ' trolley ', ' railways ', ' trolleys'],
  // '🇹🇯': ['Tajikistan ', ' Tajik flag ', ' Tadjik flag'],
  // '🇰🇵': ['North Korea ', ' North Korean flag'],
  '🎅': [
    'Santa Claus ',
    ' Santa ',
    ' Father Christmas ',
    ' old saint Nick ',
    ' Kris Kringle ',
    ' Saint Nick ',
    ' Saint Nicholas ',
    ' Mr. Claus',
  ],
  '🦃': ['turkey ', ' turkeys'],
  '🚄': ['high-speed train ', ' high-speed trains'],
  '🙇‍♂️': ['bow ', ' bowing ', ' man bowing'],
  '🔬': ['science ', ' microscope ', ' laboratory ', ' lab'],
  '🦄': ['unicorn ', ' unicorns'],
  '🎆': ['fireworks'],
  '⏰': ['alarm clock ', ' alarm clocks'],
  '♥️': ['cards ', ' hearts'],
  // '🇭🇷': ['Croatia ', ' Croatian flag'],
  '🎇': ['sparkler ', ' fireworks ', ' firework sparkler'],
  '🦅': ['eagle ', ' eagles ', ' bird ', ' birds'],
  // '🇪🇹': ['Ethiopia ', ' Ethiopian flag'],
  // '🇹🇰': ['Tokelau ', ' Tokelauan flag'],
  // '🇳🇴': ['Norway ', ' Norwegian flag'],
  '🚇': ['metro ', ' subway'],
  '🎈': ['balloon ', ' party ', ' birthday ', ' balloons ', ' parties ', ' birthdays'],
  '🦆': ['duck ', ' ducks ', ' mallard ', ' mallards'],
  '🔮': ['crystal ball ', ' fortune ', ' crystal balls ', ' fortunes'],
  // '🇪🇺': ['European Union ', ' European flag'],
  '🎉': [
    'party ',
    ' celebrate ',
    ' celebration ',
    ' birthday ',
    ' confetti ',
    ' parties ',
    ' celebrations ',
    ' birthdays ',
    ' woohoo ',
    ' hooray',
  ],
  '🦇': ['bat ', ' bats'],
  '👨‍🏭': [
    'factory worker ',
    ' welder ',
    ' manufacturing ',
    ' soldering ',
    ' man factory worker ',
    ' man welder ',
    ' man in manufacturing',
  ],
  '👮‍♀️': [
    'police ',
    ' cop ',
    ' policewoman ',
    ' constable ',
    ' police officer ',
    ' officer ',
    ' cops ',
    ' police officers ',
    ' policewomen ',
    ' constables ',
    ' officers ',
    ' popo ',
    ' 5-0',
  ],
  '🔰': ['beginner'],
  '🎊': [
    'party ',
    ' celebrate ',
    ' celebration ',
    ' birthday ',
    ' confetti ',
    ' parties ',
    ' celebrations ',
    ' birthdays',
  ],
  '🦈': ['shark ', ' sharks'],
  '⚠️': ['warning'],
  '🈲': ['prohibited'],
  // '🇧🇼': ['Botswana ', ' Botswanan flag'],
  '🎋': ['tanabata tree ', ' tanabata trees'],
  '🚊': ['train ', ' subway ', ' tram ', ' trains ', ' subways ', ' trams'],
  '🦉': ['owl ', ' owls'],
  // '🇹🇱': ['Timor-Leste ', ' Timorese flag'],
  // '🇳🇵': ['Nepal ', ' Nepalese flag'],
  '🚋': ['trolley ', ' tram ', ' trollies ', ' trams ', ' street car'],
  '🎌': ['crossed flags'],
  '🦊': ['fox ', ' foxes ', ' fox face'],
  '🈳': ['vacancy'],
  '🈴': ['passing grade'],
  '🎍': ['pine decoration ', ' pine decorations ', ' kadomatsu'],
  '🚌': ['school bus ', ' bus ', ' school busses ', ' busses'],
  '🦋': ['butterfly ', ' butterflies ', ' blue butterfly'],
  // '🇰🇷': ['South Korea ', ' South Korean flag'],
  // '🇭🇹': ['Haiti ', ' Haitian flag'],
  '🎎': ['Japanese dolls'],
  '🦌': ['deer'],
  // '🇹🇲': ['Turkmenistan ', ' Turkmen flag ', ' Turkoman flag'],
  '🈶': ['not free of charge'],
  // '🇭🇺': ['Hungary ', ' Hungarian flag'],
  '🚎': ['bus ', ' trolley ', ' busses ', ' trolleys'],
  '🎏': ['carp streamer'],
  '🦍': ['gorilla ', ' ape ', ' gorillas ', ' apes'],
  // '🇧🇾': ['Belarus ', ' Belarusian flag'],
  '🚏': ['bus stop'],
  '🎐': ['wind chime ', ' wind chimes'],
  '🦎': ['lizard ', ' lizards ', ' gecko ', ' geckos ', ' iguana ', ' iguanas ', ' reptile ', ' reptiles'],
  '🚐': ['minibus ', ' minivan'],
  '🎑': ['moon viewing ceremony'],
  '🦏': ['rhinoceros ', ' rhinoceroses ', ' rhino ', ' rhinos'],
  '🈹': ['discount'],
  // '🇧🇿': ['Belize ', ' Belizean flag'],
  '🚑': ['ambulance ', ' ambulances'],
  '🎒': ['backpack ', ' rucksack ', ' backpacks ', ' rucksacks'],
  '🦐': ['shrimp ', ' shellfish ', ' prawn ', ' prawns'],
  // '🇹🇳': ['Tunisia ', ' Tunisian flag'],
  // '🇳🇷': ['Nauru ', ' Nauruan flag'],
  '🚒': ['fire engine ', ' fire truck ', ' fireman ', ' fire engines ', ' fire trucks ', ' firemen'],
  '🎓': ['graduation ', ' graduate ', ' cap and gown ', ' graduates'],
  '🦑': ['squid ', ' giant squid ', ' mollusk ', ' mollusks ', ' tentacles'],
  '🚓': ['police ', ' cop ', ' cops'],
  '🦒': ['giraffe ', ' giraffes ', ' animal'],
  '🚔': ['police ', ' cops ', ' police car ', ' cop ', ' police cars'],
  '🦓': ['zebra ', ' zebras ', ' animal'],
  // '🇹🇴': ['Tonga ', ' Tongan flag'],
  '🎖': ['medal ', ' medals'],
  '🚕': ['taxi ', ' cab ', ' taxi cab'],
  '💇‍♀️': ['haircut ', ' salon ', ' haircuts ', ' woman haircut'],
  '🦔': ['hedgehog ', ' hedgehogs ', ' animal'],
  '👩‍✈️': [
    'pilot ',
    ' aviator ',
    ' captain ',
    ' flight attendant ',
    ' navigator ',
    ' woman pilot ',
    ' woman aviator ',
    ' woman captain ',
    ' woman flight attendant ',
    ' woman navigator ',
    ' stewardess',
  ],
  '🦕': ['dinosaur ', ' dinosaurs ', ' sauropod ', ' brachiosaurus ', ' apatosaurus ', ' brontosaurus'],
  '🚣‍♀️': ['rowboat ', ' boat ', ' rowing ', ' rowboats ', ' boats ', ' woman rowing ', ' woman rowing boat'],
  '🚗': ['car ', ' automobile ', ' hatchback ', ' vehicle ', ' cars ', ' automobiles ', ' hatchbacks ', ' vehicles'],
  '🦖': ['dinosaur ', ' dinosaurs ', ' T-Rex ', ' Tyrannosaurus Rex'],
  '⚔️': ['sword ', ' swords ', ' crossed swords'],
  '🚘': ['car ', ' sedan ', ' cars ', ' sedans'],
  '🦗': ['cricket ', ' crickets'],
  '🤸‍♂️': [
    'cartwheel ',
    ' cartwheels ',
    ' doing a cartwheel ',
    ' doing cartwheels ',
    ' man doing a cartwheel ',
    ' gymnast ',
    ' man cartwheeling ',
    ' man gymnast ',
    ' gymnasts ',
    ' cartwheeling ',
    ' gymnastics',
  ],
  '🏄‍♀️': ['surf ', ' surfing ', ' surfer ', ' surfers ', ' surf’s up ', ' hang ten ', ' woman surfing'],
  '🚙': ['car ', ' jeep ', ' SUV ', ' automobile ', ' cars ', ' jeeps ', ' SUVs ', ' automobiles'],
  // '🇳🇺': ['Niue ', ' Niuean flag'],
  // '🇰🇼': ['Kuwait ', ' Kuwaiti flag'],
  '🧟‍♂️': ['zombie ', ' zombies ', ' man zombie ', ' man zombies ', ' undead'],
  // '🇿🇲': ['Zambia ', ' Zambian flag'],
  '🚝': ['monorail'],
  '🏳️‍🌈': [
    'rainbow flag ',
    ' gay pride flag ',
    ' LGBT pride flag ',
    ' gay pride ',
    ' LGBT pride ',
    ' GLBT ',
    ' LGBT ',
    ' LGBTQ ',
    ' pride parade',
  ],
  // '🇹🇷': ['Turkey ', ' Turkish flag'],
  '🎡': ['ferris wheel ', ' carnival ', ' ferris wheels ', ' carnivals'],
  '🎢': ['rollercoaster ', ' rollercoasters'],
  // '🇰🇾': ['Cayman Islands ', ' Cayman Island flag'],
  '🎣': ['fishing ', ' fishing pole ', ' fish'],
  '🚢': ['ship ', ' cruise ship ', ' cruise ', ' vessel ', ' ships ', ' cruise ships ', ' cruises ', ' vessels'],
  '🕊': ['dove ', ' doves ', ' olive branch'],
  '🎤': ['karaoke ', ' sing ', ' mic ', ' microphone ', ' singing ', ' microphones'],
  '🚤': [
    'boat ',
    ' speedboat ',
    ' powerboat ',
    ' motorboat ',
    ' boats ',
    ' speedboats ',
    ' powerboats ',
    ' motorboats',
  ],
  '🎥': ['movie ', ' camera ', ' movies ', ' cameras'],
  '✂️': ['scissors'],
  '🕌': ['mosque ', ' mosques'],
  '🚥': ['traffic light ', ' traffic lights'],
  // '🇹🇹': [
  //   'Trinidad & Tobago ',
  //   ' Trinidad and Tobago ',
  //   ' Trinidad ',
  //   ' Tobago ',
  //   ' Trinidadian flag ',
  //   ' Tobagonian flag',
  // ],
  // '🇰🇿': ['Kazakhstan ', ' Kazakh flag'],
  '🧛‍♀️': ['woman vampire ', ' woman vampires ', ' vampire ', ' vampires ', ' undead'],
  '🕍': ['synagogue ', ' synagogues'],
  '🎧': ['EarPods ', ' music ', ' headphone ', ' headphones'],
  '🚦': ['traffic light ', ' traffic lights'],
  '🧘‍♂️': ['yoga ', ' yogi ', ' lotus position ', ' meditation ', ' man in lotus position'],
  '🎨': ['artist ', ' paint ', ' palette ', ' tray ', ' palettes'],
  '🚧': ['construction sign ', ' construction ', ' roadwork'],
  '🎩': ['hat ', ' magician ', ' wedding ', ' hats ', ' magicians ', ' weddings'],
  '🚨': ['sirens ', ' police ', ' emergency ', ' alarm ', ' alert ', ' siren ', ' alarms'],
  // '🇼🇸': ['Samoa ', ' Samoan flag'],
  '🕐': ['01:[00 ', ' 13:[00 ', ' 1:[00 ', ' one o’clock'],
  '🕑': ['02:[00 ', ' 14:[00 ', ' 2:[00 ', ' two o’clock'],
  '🚪': ['door ', ' doors'],
  '🕒': ['03:[00 ', ' 15:[00 ', ' 3:[00 ', ' three o’clock'],
  '🎬': ['clapper board ', ' clapper boards'],
  '🚫': ['forbidden ', ' prohibited'],
  '🕓': ['04:[00 ', ' 16:[00 ', ' 4:[00 ', ' four o’clock'],
  '🎭': ['theatre ', ' theater ', ' thespians ', ' arts ', ' masks ', ' Broadway ', ' theaters ', ' thespian'],
  // '🇹🇻': ['Tuvalu ', ' Tuvaluan flag'],
  // '🇳🇿': ['New Zealand ', ' New Zealand flag'],
  '🕔': ['05:[00 ', ' 17:[00 ', ' 5:[00 ', ' five o’clock'],
  '🎮': ['video game ', ' video game controller ', ' console game ', ' console controller'],
  '🚵‍♀️': [
    'cyclist ',
    ' bicyclist ',
    ' cycling ',
    ' biking ',
    ' biker ',
    ' bikers ',
    ' cyclists ',
    ' bicyclists ',
    ' mountain bike ',
    ' mountain biking ',
    ' woman biking',
  ],
  '🚭': ['no smoking ', ' don’t smoke'],
  '☎️': ['telephone ', ' phone ', ' telephones ', ' phones'],
  '🕕': ['06:[00 ', ' 18:[00 ', ' 6:[00 ', ' six o’clock'],
  '🎯': ['darts ', ' bullseye ', ' dart ', ' bullseyes ', ' target'],
  '🕖': ['07:[00 ', ' 19:[00 ', ' 7:[00 ', ' seven o’clock'],
  // '🇹🇼': ['Taiwan ', ' Taiwanese flag ', ' Republic of China'],
  '🕗': ['08:[00 ', ' 20:[00 ', ' 8:[00 ', ' eight o’clock'],
  '🎱': ['pool ', ' billiards ', ' eight ball ', ' snooker ', ' ball ', ' balls'],
  '⛺️': [
    'tent ',
    ' camping ',
    ' base camp ',
    ' campground ',
    ' tepee ',
    ' teepee ',
    ' yurt ',
    ' tents ',
    ' base camps ',
    ' campgrounds ',
    ' tepees ',
    ' teepees ',
    ' yurts',
  ],
  '🕘': ['09:[00 ', ' 21:[00 ', ' 9:[00 ', ' nine o’clock'],
  '🎲': ['dice'],
  '🐀': ['rat ', ' rats'],
  '🕙': ['10:[00 ', ' 22:[00 ', ' ten o’clock'],
  '🎳': ['bowling ', ' bowling pins ', ' bowling ball ', ' bowling pin ', ' bowling balls ', ' ball'],
  '🐁': ['mouse ', ' mice'],
  '🚲': ['bike ', ' bicycle ', ' bikes ', ' bicycles'],
  '🕚': ['11:[00 ', ' 23:[00 ', ' eleven o’clock'],
  '🏌️‍♀️': ['golf ', ' golfer ', ' golfers ', ' golfing ', ' woman golfing'],
  '🐂': ['ox ', ' oxen'],
  '🕛': ['0:[00 ', ' 12:[00 ', ' 24:[00 ', ' twelve o’clock ', ' midnight ', ' noon'],
  '🎵': ['sing ', ' music'],
  '🕜': ['01:[30 ', ' 13:[30 ', ' 1:[30 ', ' one thirty'],
  '🎶': ['sing ', ' music'],
  '🐄': ['cow ', ' cattle ', ' cows'],
  '🕝': ['02:[30 ', ' 14:[30 ', ' 2:[30 ', ' two thirty'],
  '🎷': ['saxophone ', ' sax ', ' instrument ', ' music ', ' saxophones'],
  '🐅': ['tiger ', ' tigers'],
  // '🇦🇩': ['Andorra ', ' Andorran flag'],
  '🕞': ['03:[30 ', ' 15:[30 ', ' 3:[30 ', ' three thirty'],
  '🎸': [
    'electric guitar ',
    ' guitar ',
    ' rock and roll ',
    ' guitars ',
    ' electric guitars ',
    ' musical instrument ',
    ' musical instruments',
  ],
  '🤦‍♀️': [
    'face palm ',
    ' face palming ',
    ' woman doing a face palm ',
    ' woman face palming ',
    ' hand on face ',
    ' smh ',
    ' SMH ',
    ' oh no ',
    ' don’t tell me ',
    ' say it isn’t so ',
    ' facepalm ',
    ' why did I do that ',
    ' face palm woman ',
    ' woman face palm',
  ],
  '🕟': ['04:[30 ', ' 16:[30 ', ' 4:[30 ', ' four thirty'],
  '🎹': ['keyboard ', ' keys ', ' music ', ' keyboards ', ' piano ', ' pianos'],
  '🐇': ['rabbit ', ' rabbits'],
  '🕠': ['05:[30 ', ' 17:[30 ', ' 5:[30 ', ' five thirty'],
  '🎺': ['trumpet ', ' instrument ', ' music ', ' trumpets ', ' instruments'],
  '🐈': ['cat ', ' cats'],
  '🕡': ['06:[30 ', ' 18:[30 ', ' 6:[30 ', ' six thirty'],
  // '🇹🇿': ['Tanzania ', ' Tanzanian flag'],
  '🎻': ['violin ', ' instrument ', ' music ', ' violins ', ' instruments'],
  '🐉': ['dragon ', ' dragons'],
  // '🇬🇦': ['Gabon ', ' Gabonese flag'],
  // '🇦🇪': ['United Arab Emirates ', ' UAE ', ' UAE flag ', ' Emirates flag ', ' Emirati flag'],
  '🕢': ['07:[30 ', ' 19:[30 ', ' 7:[30 ', ' seven thirty'],
  '🎼': ['treble clef ', ' music ', ' music score ', ' musical score'],
  '🙇‍♀️': ['bow ', ' bowing ', ' woman bowing'],
  '🕣': ['08:[30 ', ' 20:[30 ', ' 8:[30 ', ' eight thirty'],
  '🅰️': ['blood type A'],
  '🐋': ['whale ', ' humpback ', ' whales ', ' humpbacks ', ' humpback whale ', ' humpback whales'],
  '🕤': ['09:[30 ', ' 21:[30 ', ' 9:[30 ', ' nine thirty'],
  '🎾': ['tennis ball ', ' tennis ', ' ball ', ' balls ', ' tennis balls'],
  '🐌': ['snail ', ' escargot ', ' slug ', ' snails ', ' slugs'],
  '🚽': [
    'toilet ',
    ' toilets ',
    ' WC ',
    ' bathroom ',
    ' bathrooms ',
    ' restroom ',
    ' restrooms ',
    ' potty ',
    ' potties ',
    ' the loo ',
    ' porcelain throne ',
    ' pooper ',
    ' crapper ',
    ' crappers',
  ],
  // '🇬🇧': [
  //   'United Kingdom ',
  //   ' UK ',
  //   ' Britain ',
  //   ' Great Britain ',
  //   ' Union Jack ',
  //   ' GB ',
  //   ' British flag ',
  //   ' UK flag',
  // ],
  // '🇦🇫': ['Afghanistan ', ' Afghan flag'],
  '🎿': ['ski ', ' skis ', ' ski boot ', ' ski boots'],
  '🐍': ['snake ', ' python ', ' cobra ', ' snakes ', ' pythons ', ' cobras'],
  '🕥': ['10:[30 ', ' 22:[30 ', ' ten thirty'],
  '🕦': ['11:[30 ', ' 23:[30 ', ' eleven thirty'],
  '🇿🇼': ['Zimbabwe ', ' Zimbabwean flag'],
  '🏀': ['basketball ', ' basketballs ', ' ball ', ' balls'],
  '🐎': ['horse ', ' derby ', ' horses ', ' horse race ', ' horse races'],
  '🚿': ['shower ', ' water ', ' shower head ', ' showers ', ' shower heads'],
  '🕧': ['0:[30 ', ' 12:[30 ', ' twelve thirty'],
  '🛀': ['bubble bath ', ' bath ', ' bathtub ', ' tub ', ' baths ', ' bathtubs'],
  '🏁': ['checkered flag ', ' finish line'],
  // '🇩🇪': ['Germany ', ' German flag'],
  '🧀': ['cheese ', ' cheese wedge ', ' Swiss ', ' cheeses'],
  '🐐': ['goat ', ' goats'],
  '🏂': ['snowboarder ', ' snowboarding ', ' on the slopes'],
  // '🇦🇬': ['Antigua & Barbuda ', ' Antigua and Barbuda ', ' Antiguan flag ', ' Barbudan flag'],
  '🐑': ['sheep ', ' ram ', ' rams'],
  '❤️': ['love ', ' heart'],
  '🐒': ['monkey ', ' monkeys'],
  '🏅': ['medal ', ' medals'],
  '🐓': ['rooster ', ' roosters ', ' chicken ', ' chickens'],
  // '🇬🇩': ['Grenada ', ' Grenadian flag'],
  '🤼‍♂️': [
    'wrestler ',
    ' wrestlers ',
    ' two men wrestling ',
    ' wrestling ',
    ' wrestling match ',
    ' men wrestling ',
    ' two wrestlers',
  ],
  '🏆': ['trophy ', ' trophies'],
  '🐔': ['chicken ', ' rooster ', ' chickens ', ' roosters'],
  '☹️': [
    'sad ',
    ' bummed ',
    ' hurt ',
    ' frown face ',
    ' frowny face ',
    ' sad emoji ',
    ' sad face ',
    ' disappointed ',
    ' lonely ',
    ' feel bad ',
    ' downcast ',
    ' long face ',
    ' somber ',
    ' solemn ',
    ' melancholy ',
    ' dejected ',
    ' glum ',
    ' gloomy ',
    ' dreary ',
    ' unhappy ',
    ' sorrowful ',
    ' miserable ',
    ' bummed out',
  ],
  '🐕': ['dog ', ' dogs'],
  '🏈': ['football ', ' footballs ', ' ball ', ' balls'],
  '🐖': ['pig ', ' pigs'],
  // '🇬🇪': ['Georgia ', ' Georgian flag'],
  // '🇦🇮': ['Anguilla ', ' Anguillan flag'],
  '🏉': ['rugby ', ' rugby football'],
  '🐗': ['boar ', ' boars'],
  // '🇲🇦': ['Morocco ', ' Moroccan flag'],
  '🐘': ['elephant ', ' Dumbo ', ' mammoth ', ' elephants ', ' mammoths'],
  '🐙': ['tentacle ', ' octopus ', ' octopuses ', ' octopi ', ' tentacles'],
  '🛋': ['couch ', ' sofa'],
  '🐚': ['shell ', ' hermit crab ', ' snail shell ', ' shells ', ' hermit crabs ', ' snail shells'],
  // '🇬🇫': ['French Guiana ', ' French Guianese flag'],
  '🏍': ['motorcycle ', ' motorbike ', ' moped ', ' bike ', ' motorcycles ', ' motorbikes ', ' mopeds ', ' bikes'],
  '🐛': ['bug ', ' worm ', ' caterpillar ', ' bugs ', ' worms ', ' caterpillars'],
  '🏎': [
    'race car ',
    ' race cars ',
    ' racing car ',
    ' racing cars ',
    ' formula 1 ',
    ' formula one ',
    ' formula 1 car ',
    ' formula 1 cars ',
    ' formula one car ',
    ' formula one cars',
  ],
  '🐜': ['ant ', ' bug ', ' insect ', ' ants ', ' bugs ', ' insects'],
  '🏏': ['cricket bat ', ' cricket'],
  '🐝': [
    'bzz ',
    ' bzzz ',
    ' bzzzz ',
    ' bzzzzz ',
    ' bumble bee ',
    ' bee ',
    ' hornet ',
    ' yellow jacket ',
    ' bumble bees ',
    ' bees ',
    ' hornets ',
    ' yellow jackets',
  ],
  '🛎': ['bellhop ', ' bell ', ' bellhop bell'],
  '🕶': ['sunglasses'],
  // '🇬🇬': ['Guernsey ', ' Channel Island flag'],
  '🏐': ['volleyball ', ' volleyballs ', ' ball ', ' balls'],
  // '🐞': ['ladybug ', ' insect ', ' bug ', ' ladybugs ', ' insects ', ' bugs'],
  '🛏': [
    'bed ',
    ' beds ',
    ' sleep ',
    ' sleeping ',
    ' sleeps ',
    ' slept ',
    ' snooze ',
    ' snoozing ',
    ' snoozed ',
    ' snoozes ',
    ' hit the hay ',
    ' hit the sack',
  ],
  '🕷': ['spider ', ' insect ', ' bug ', ' arachnid ', ' spiders ', ' insects ', ' bugs ', ' arachnids'],
  // '🇯🇪': ['Jersey flag ', ' Channel Island flag'],
  '🏑': ['field hockey'],
  '🐟': ['fish'],
  // '🇲🇨': ['Monaco ', ' Monégasque flag ', ' Monacan flag'],
  // '🇵🇦': ['Panama ', ' Panamanian flag'],
  '🤸‍♀️': [
    'cartwheel ',
    ' cartwheels ',
    ' doing a cartwheel ',
    ' doing cartwheels ',
    ' woman doing a cartwheel ',
    ' woman cartwheeling ',
    ' woman gymnast ',
    ' gymnast ',
    ' gymnasts ',
    ' cartwheeling ',
    ' gymnastics',
  ],
  '🏒': ['ice hockey ', ' hockey ', ' hockey stick'],
  '🐠': ['fish ', ' tropical'],
  '🛑': ['stop sign ', ' red sign ', ' octagonal sign ', ' red octagonal sign ', ' stop'],
  '👩‍🚀': ['astronaut ', ' cosmonaut ', ' woman astronaut'],
  // '🇩🇯': ['Djibouti ', ' Djiboutian flag'],
  '🏓': ['table tennis ', ' ping pong ', ' ping pong paddle ', ' table tennis racket'],
  '🐡': ['blowfish'],
  // '🇦🇱': ['Albania ', ' Albanian flag'],
  // '🇬🇭': ['Ghana ', ' Ghanaian flag'],
  // '🇲🇩': ['Moldova ', ' Moldovan flag'],
  '🕺': ['dancer ', ' man dancer ', ' dancing man ', ' dancing ', ' man dancing ', ' Elvis ', ' elvis'],
  '🐢': ['turtle ', ' turtles'],
  '🛒': [
    'cart ',
    ' carts ',
    ' shopping cart ',
    ' shopping carts ',
    ' shopping trolley ',
    ' shopping trollies ',
    ' shopping',
  ],
  '🧐': ['monocle'],
  '🧒': ['child ', ' young person ', ' kid'],
  '🧓': ['older adult ', ' older person ', ' elder ', ' senior citizen'],
  '🐣': ['chick ', ' baby duckling ', ' Easter ', ' chicks ', ' baby ducklings ', ' hatch ', ' hatching ', ' hatched'],
  '🧜‍♂️': ['merman ', ' Triton'],
  '🧟‍♀️': ['zombie ', ' zombies ', ' woman zombie ', ' woman zombies ', ' undead'],
  '🏖': ['beach ', ' beach umbrella'],
  '🐤': ['chick ', ' chicks ', ' baby chick ', ' baby chicks ', ' chickadee ', ' chickadees'],
  // '🇩🇰': ['Denmark ', ' Danish flag'],
  // '🇦🇲': ['Armenia ', ' Armenian flag'],
  // '🇬🇮': ['Gibraltar ', ' Gibraltar flag'],
  // '🇲🇪': ['Montenegro ', ' Montenegrin flag'],
  '🐥': ['duckling ', ' chicks ', ' ducklings ', ' chick ', ' chickadee ', ' chickadees'],
  // '🇸🇦': ['Saudi Arabia ', ' Saudi Arabian flag ', ' Saudi flag'],
  '🧕': ['headscarf ', ' hijab'],
  '🧔': ['bearded ', ' beard'],
  '🐦': ['bird ', ' birds'],
  '♨️': ['hot springs ', ' hot spring ', ' onsen ', ' onsens'],
  '🐧': ['penguin ', ' penguins'],
  // '🇸🇧': ['Solomon Islands ', ' Solomon Island flag'],
  '🚶‍♂️': [
    'pedestrian ',
    ' walking ',
    ' strolling ',
    ' stroll ',
    ' taking a walk ',
    ' pedestrians ',
    ' get away ',
    ' man walking',
  ],
  '🐨': ['koala ', ' koalas'],
  '🐩': ['poodle ', ' poodles'],
  '👩‍🏫': [
    'teacher ',
    ' teachers ',
    ' professor ',
    ' professors ',
    ' lecturer ',
    ' educator ',
    ' educators ',
    ' schoolteacher ',
    ' schoolteachers ',
    ' prof ',
    ' faculty member ',
    ' faculty members ',
    ' instructor ',
    ' instructors ',
    ' scholar ',
    ' scholars ',
    ' woman teacher ',
    ' woman teachers ',
    ' woman professor ',
    ' woman professors ',
    ' woman lecturer ',
    ' woman educator ',
    ' woman educators ',
    ' woman schoolteacher ',
    ' woman schoolteachers ',
    ' woman faculty member',
  ],
  '🐪': ['camel ', ' desert ', ' camels'],
  '🧘‍♀️': ['yoga ', ' yogi ', ' lotus position ', ' meditation ', ' woman in lotus position'],
  '🏝': ['desert island ', ' palm tree ', ' tropical ', ' beach ', ' tropical island'],
  '🐫': ['camel ', ' desert ', ' camels'],
  // '🇩🇲': ['Dominica ', ' Dominican flag'],
  // '🇦🇴': ['Angola ', ' Angolan flag'],
  // '🇲🇬': ['Madagascar ', ' Malagasy flag'],
  // '🇵🇪': ['Peru ', ' Peruvian flag'],
  '🐬': ['dolphin ', ' porpoise ', ' dolphins ', ' porpoises'],
  // '🇸🇨': ['Seychelles ', ' Seychellois flag'],
  // '🇻🇦': ['Holy See ', ' Vatican ', ' Vatican flag'],
  '🐭': ['mouse ', ' mice'],
  '👨‍💻': [
    'technology worker ',
    ' tech worker ',
    ' technologist ',
    ' techie ',
    ' IT worker ',
    ' Apple genius ',
    ' man in technology ',
    ' man tech worker ',
    ' man technologist ',
    ' man IT worker ',
    ' man in IT ',
    ' man Apple genius',
  ],
  '🏠': [
    'home ',
    ' house ',
    ' townhouse ',
    ' townhome ',
    ' town home ',
    ' homes ',
    ' houses ',
    ' townhouses ',
    ' townhomes ',
    ' town homes',
  ],
  '🐮': ['cow ', ' cows ', ' cattle'],
  // '🇬🇱': ['Greenland ', ' Greenlandic flag'],
  // '🇲🇭': ['Marshall Islands ', ' Marshall Island flag'],
  // '🇵🇫': ['French Polynesia ', ' French Polynesian flag'],
  '🏡': [
    'home ',
    ' house ',
    ' townhouse ',
    ' townhome ',
    ' town home ',
    ' estate ',
    ' homes ',
    ' houses ',
    ' townhouses ',
    ' townhomes ',
    ' town homes ',
    ' estates',
  ],
  '🐯': ['tiger ', ' roar ', ' rawr ', ' rwar ', ' tigers'],
  // '🇸🇩': ['Sudan ', ' Sudanese flag'],
  '🧠': ['brain ', ' brains'],
  '🐰': ['rabbit ', ' bunny ', ' rabbits ', ' bunnies'],
  '⛈': ['lightning ', ' thunderstorm ', ' thunderstorms ', ' storm ', ' stormy ', ' thunder storm ', ' rain storm'],
  '🏣': ['Japanese post office'],
  '🐱': ['kitten ', ' cat ', ' kitty ', ' meow ', ' kittens ', ' cats ', ' kitties'],
  '🧡': ['orange heart ', ' orange hearts'],
  // '🇩🇴': ['Dominican Republic ', ' Dominican flag'],
  '♠️': ['playing card ', ' playing cards ', ' spade ', ' spades'],
  '🐲': ['dragon head ', ' dragon heads'],
  // '🇦🇶': ['Antarctica ', ' Antarctic flag'],
  // '🇬🇲': ['Gambia ', ' Gambian flag'],
  // '🇵🇬': ['Papua New Guinea ', ' Papua New Guinean flag ', ' Papuan flag'],
  // '🇸🇪': ['Sweden ', ' Swedish flag'],
  '🐳': ['whale ', ' whales'],
  // '🇻🇨': [
  //   'Saint Vincent & Grenadines ',
  //   ' Saint Vincent and Grenadines ',
  //   ' Saint Vincentian flag ',
  //   ' Vincentian flag ',
  //   ' Grenadine flag',
  // ],
  '🖌': ['paintbrush ', ' paintbrushes'],
  '🧣': ['scarf ', ' scarves'],
  '🧤': ['glove ', ' gloves'],
  '🐴': ['horse ', ' horses'],
  '🙋‍♀️': ['hand up ', ' raising hand'],
  '👨‍💼': [
    'office worker ',
    ' insurance agent ',
    ' salesman ',
    ' paper pusher ',
    ' clerical worker ',
    ' admin ',
    ' administrative worker ',
    ' secretary ',
    ' CEO ',
    ' CFO ',
    ' CPA ',
    ' CTO ',
    ' man office worker ',
    ' man insurance agent ',
    ' man clerical worker ',
    ' man admin ',
    ' man administrative worker ',
    ' man secretary ',
    ' man CEO ',
    ' man CFO ',
    ' man CPA ',
    ' man CTO',
  ],
  '⛏': ['pick axe ', ' pick axes ', ' mining'],
  '🏧': ['ATM ', ' ATMs'],
  '🐵': ['monkey ', ' monkeys'],
  // '🇦🇷': ['Argentina ', ' Argentinian flag'],
  // '🇬🇳': ['Guinea ', ' Guinean flag'],
  // '🇵🇭': ['Philippines ', ' Filipino flag ', ' Philippine flag'],
  '👨‍🎓': [
    'student ',
    ' graduate ',
    ' pupil ',
    ' man student ',
    ' man graduate ',
    ' man pupil ',
    ' graduation ',
    ' graduation day ',
    ' alumnus ',
    ' alumni ',
    ' alma mater',
  ],
  '🐶': ['puppy ', ' dog ', ' puppies ', ' dogs ', ' doggie'],
  '👨‍🚒': ['firefighter ', ' man firefighter'],
  '🧥': ['coat ', ' coats ', ' jacket ', ' jackets'],
  '👩‍🏭': [
    'factory worker ',
    ' welder ',
    ' manufacturing ',
    ' soldering ',
    ' woman factory worker ',
    ' woman welder ',
    ' woman in manufacturing',
  ],
  '🧦': ['socks'],
  '🐷': ['oink ', ' pig ', ' piggy ', ' porky ', ' pigs ', ' piggies'],
  '🧢': ['hat ', ' hats ', ' cap ', ' caps'],
  '🐸': ['frog ', ' frogs'],
  // '🇦🇸': ['American Samoa ', ' American Samoan flag'],
  // '🇯🇲': ['Jamaica ', ' Jamaican flag'],
  // '🇲🇰': ['Macedonia ', ' Macedonian flag'],
  '🐹': ['hamster ', ' hamsters'],
  // '🇸🇬': ['Singapore ', ' Singaporean flag'],
  '✍️': ['drawing ', ' writing ', ' pen in hand'],
  '🅿️': ['parking ', ' parking sign'],
  '🛫': [
    'takeoff ',
    ' plane is taking off ',
    ' for takeoff ',
    ' flight leaves ',
    ' flight departs ',
    ' flight will depart ',
    ' flight is departing ',
    ' plane is departing ',
    ' plane departs ',
    ' plane takes off ',
    ' plane will take off ',
    ' plane takeoff ',
    ' wheels up',
  ],
  '🐺': ['wolf ', ' wolves'],
  // '🇻🇪': ['Venezuela ', ' Venezuelan flag'],
  '🛬': [
    'plane is landing ',
    ' plane just landed ',
    ' we just landed ',
    ' we’re landing ',
    ' we’ll be landing ',
    ' we landed ',
    ' plane landed ',
    ' flight arrival ',
    ' plane arrival ',
    ' airplane arrival ',
    ' wheels down',
  ],
  '🐻': ['bear ', ' bears'],
  '⌚️': ['Apple watch ', ' Apple watches ', ' wristwatch ', ' wristwatches ', ' wrist watch ', ' wrist watches'],
  '🏮': ['izakaya ', ' izakaya lantern'],
  '🐼': ['panda ', ' pandas'],
  // '🇦🇹': ['Austria ', ' Austrian flag'],
  // '🇬🇵': ['Guadeloupe ', ' Guadeloupe flag'],
  // '🇲🇱': ['Mali ', ' Malian flag'],
  '☝️': ['pointing ', ' I agree ', ' one ', ' one second ', ' excuse me'],
  '🐽': ['pig ', ' pigs'],
  '🏯': ['Japanese castle'],
  '🖖': ['live long and prosper ', ' Vulcan ', ' Vulcan salute ', ' Spock'],
  // '🇸🇭': ['Saint Helena ', ' Saint Helenian flag'],
  '🐾': ['paw ', ' paws ', ' paw print ', ' paw prints'],
  '⚓️': ['ship anchor ', ' ship anchors ', ' ship’s anchor ', ' ship’s anchors'],
  '🛰': ['satellite ', ' satellites'],
  '✉️': ['envelope ', ' envelopes'],
  // '🇦🇺': ['Australia ', ' Australian flag'],
  // '🇬🇶': ['Equatorial Guinea ', ' Equatorial Guinean flag ', ' Equatoguinean flag'],
  '❄️': ['snow ', ' snowflake ', ' winter ', ' icy ', ' ice cold ', ' snowflakes'],
  '👀': ['eyes ', ' look ', ' spying ', ' I see you ', ' eye balls ', ' creeper ', ' stalker ', ' peep'],
  // '🇯🇴': ['Jordan ', ' Jordanian flag'],
  // '🇲🇲': ['Myanmar ', ' Burma ', ' Burmese flag'],
  // '🇵🇰': ['Pakistan ', ' Pakistani flag'],
  // '🇸🇮': ['Slovenia ', ' Slovene flag ', ' Slovenian flag'],
  // '👁': ['eye ', ' eyeball'],
  // '🇻🇬': ['British Virgin Islands ', ' Virgin Islands ', ' British Virgin Islands flag'],
  // '🇾🇪': ['Yemen ', ' Yemeni flag'],
  '👂': ['ear ', ' lobe ', ' hear ', ' ears ', ' lobes ', ' listen ', ' listening ', ' listen to me'],
  // '🇬🇷': ['Greece ', ' Greek flag'],
  // '🇯🇵': ['Japan ', ' Japanese flag'],
  '👃': ['nose ', ' nostril ', ' noses ', ' nostrils'],
  // '🇲🇳': ['Mongolia ', ' Mongolian flag'],
  // '🇵🇱': ['Poland ', ' Polish flag'],
  '🛴': ['scooter ', ' scooters ', ' razor scooter ', ' razor scooters'],
  '🛵': ['motor scooter ', ' motor scooters ', ' vespa ', ' vespas'],
  '👄': ['mouth ', ' lips ', ' mouths'],
  '⛩': ['Shinto shrine'],
  '⛪': ['church ', ' churches'],
  '👅': ['tongue ', ' lick'],
  '🛶': ['canoe ', ' canoes ', ' green canoe ', ' boating ', ' canoeing'],
  '👨‍🔧': ['mechanic ', ' technician ', ' man mechanic ', ' man technician'],
  '🏸': ['badminton ', ' badminton racquet ', ' badminton racket ', ' shuttlecock'],
  '👆': ['point up ', ' points up ', ' pointing up ', ' up there'],
  // '🇦🇼': ['Aruba ', ' Aruban flag'],
  // '🇬🇸': [
  //   'South Georgia & the South Sandwich Islands ',
  //   ' South Georgia and the South Sandwich Islands ',
  //   ' South Georgia flag ',
  //   ' South Sandwich Islands flag',
  // ],
  // '🇲🇴': ['Macau ', ' Macanese flag'],
  '🏹': ['bow and arrow ', ' archery'],
  '👇': ['point down ', ' points down ', ' pointing down ', ' down there'],
  // '🇵🇲': ['Saint Pierre & Miquelon ', ' Saint Pierre and Miquelon ', ' Saint-Pierrais flag ', ' Miquelonnais flag'],
  // '🇸🇰': ['Slovakia ', ' Slovak flag'],
  // '🇻🇮': [
  //   'U.S. Virgin Islands ',
  //   ' US Virgin Islands ',
  //   ' Virgin Islands ',
  //   ' U.S. Virgin Islands flag ',
  //   ' US Virgin Islands flag',
  // ],
  '🛸': ['UFO ', ' UFOs ', ' flying saucer ', ' flying saucers'],
  '👈': ['point left ', ' points left ', ' pointing left ', ' over here'],
  '🛷': ['sled ', ' sleds ', ' sleigh ', ' sleighs'],
  '⛰': ['mountain ', ' mountains'],
  '☕️': ['coffee ', ' tea ', ' chai ', ' teacup ', ' coffee cup'],
  '🏋️‍♀️': [
    'weightlifting ',
    ' weight lifting ',
    ' weight lifter ',
    ' weightlifter ',
    ' clean and jerk ',
    ' lift weights ',
    ' lifting weights ',
    ' working out ',
    ' work out ',
    ' woman lifting weights',
  ],
  '⛱': ['beach umbrella ', ' beach umbrellas'],
  '👉': ['point right ', ' points right ', ' pointed right ', ' over there'],
  // '🇦🇽': ['Åland Islands ', ' Åland Island flag'],
  // '🇬🇹': ['Guatemala ', ' Guatemalan flag'],
  // '🇲🇵': ['Northern Mariana Islands ', ' Northern Marianan flag'],
  '👊': ['fist ', ' fist bump ', ' fists ', ' dap ', ' boom pow'],
  // '🇵🇳': ['Pitcairn ', ' Pitcairn flag'],
  // '🇸🇱': ['Sierra Leone ', ' Sierra Leonian flag'],
  '🤼‍♀️': [
    'wrestler ',
    ' wrestlers ',
    ' two women wrestling ',
    ' wrestling ',
    ' wrestling match ',
    ' women wrestling ',
    ' two wrestlers',
  ],
  '⛴': ['ferry ', ' ferries'],
  '👋': [
    'bye ',
    ' hi ',
    ' hello ',
    ' see ya ',
    ' bye bye ',
    ' hey ',
    ' slap ',
    ' wave ',
    ' waving ',
    ' goodbye ',
    ' wave goodbye ',
    ' waving goodbye ',
    ' see you later ',
    ' TTFN',
  ],
  '🤹‍♂️': ['juggling ', ' man juggling ', ' juggling balls ', ' juggler'],
  '🖤': ['heart ', ' black heart'],
  '👌': ['ok ', ' perfect ', ' okay ', ' sounds good ', ' dece ', ' A-OK'],
  '🖥': ['iMac ', ' desktop computer ', ' desktop computers ', ' computer ', ' computers ', ' Mac'],
  '⛷': ['skier ', ' skiers ', ' skiing ', ' ski slopes ', ' on the slopes'],
  // '🇬🇺': ['Guam ', ' Guamanian flag'],
  '👍': ['ok ', ' yep ', ' great ', ' nice ', ' thumbs up ', ' good job ', ' well done ', ' sounds good'],
  '⛸': ['ice skate ', ' ice skating ', ' figure skating'],
  // '🇲🇶': ['Martinique ', ' Martiniquais flag'],
  // '🇸🇲': ['San Marino ', ' Sammarinese flag'],
  '👎': ['nope ', ' thumbs down ', ' negative'],
  '👏': [
    'clapping ',
    ' applause ',
    ' awesome ',
    ' clap ',
    ' good job ',
    ' bravo ',
    ' yay ',
    ' clap your hands ',
    ' give yourself a hand',
  ],
  '💁‍♀️': [
    'hairdo ',
    ' hairstyle ',
    ' updo ',
    ' hair appointment ',
    ' my hair done ',
    ' diva ',
    ' hair flick ',
    ' hair toss ',
    ' hair flip ',
    ' sassy ',
    ' concierge ',
    ' bellhop ',
    ' information desk woman',
  ],
  // '🇦🇿': ['Azerbaijan ', ' Azerbaijani flag'],
  // '🇲🇷': ['Mauritania ', ' Mauritanian flag'],
  '⛽️': ['gas ', ' fuel pump ', ' gas station ', ' petrol ', ' fuel pumps ', ' gas stations ', ' fuel'],
  // '🇸🇳': ['Senegal ', ' Senegalese flag'],
  '👑': ['crown ', ' king ', ' queen ', ' royal ', ' prince ', ' princess'],
  '㊗️': ['congratulations'],
  '👒': ['woman’s hat ', ' ladies hat'],
  '👓': ['glasses ', ' spectacles'],
  // '🇬🇼': ['Guinea-Bissau ', ' Bissau-Guinean flag'],
  '🈚️': ['free of charge'],
  '👔': ['necktie ', ' shirt ', ' neckties ', ' shirts ', ' dress shirt ', ' dress shirts'],
  // '🇲🇸': ['Montserrat ', ' Montserratan flag'],
  // '🇸🇴': ['Somalia ', ' Somali flag'],
  '✅': ['check mark ', ' done'],
  '👕': ['shirt ', ' polo ', ' shirts ', ' polos'],
  '🧙‍♂️': [
    'mage ',
    ' mages ',
    ' wizard ',
    ' wizards ',
    ' magical ',
    ' sorcerer ',
    ' sorcerers ',
    ' enchanter ',
    ' enchanters ',
    ' necromancer ',
    ' necromancers ',
    ' man mage ',
    ' Merlin',
  ],
  '🧜‍♀️': ['mermaid ', ' mermaids'],
  '⚾️': ['baseball ', ' baseballs ', ' ball ', ' balls'],
  '👖': ['jeans ', ' pants ', ' slacks'],
  '👗': ['dress ', ' dresses'],
  // '🇩🇿': ['Algeria ', ' Algerian flag'],
  // '🇲🇹': ['Malta ', ' Maltese flag'],
  // '🇵🇷': ['Puerto Rico ', ' Puerto Rican flag'],
  // '🇻🇳': ['Vietnam ', ' Vietnamese flag'],
  '✊': ['respect'],
  '✋': ['stop ', ' high five'],
  '👙': ['bikini ', ' bathing suit ', ' bikinis ', ' bathing suits'],
  '👷‍♂️': ['construction worker ', ' construction workers'],
  '👚': ['shirt ', ' blouse ', ' shirts ', ' blouses'],
  // '🇬🇾': ['Guyana ', ' Guyanese flag'],
  // '🇲🇺': ['Mauritius ', ' Mauritian flag'],
  // '🇵🇸': ['Palestinian Territories ', ' Palestinian flag ', ' Palestine ', ' State of Palestine'],
  '👛': ['purse ', ' purses'],
  '👜': ['handbag ', ' purse ', ' tote ', ' handbags ', ' purses ', ' totes'],
  '⛵️': ['sailboat ', ' boat ', ' dinghy ', ' sailing ', ' sailboats ', ' boats ', ' dinghies'],
  '🚶‍♀️': [
    'pedestrian ',
    ' walking ',
    ' strolling ',
    ' stroll ',
    ' taking a walk ',
    ' pedestrians ',
    ' get away ',
    ' woman walking',
  ],
  '🕵️‍♀️': ['spy ', ' spying ', ' sleuth ', ' sleuthing ', ' Sherlock ', ' Sherlock Holmes'],
  // '🇲🇻': ['Maldives ', ' Maldivian flag'],
  '👞': ['shoe ', ' Oxfords ', ' loafers ', ' shoes'],
  // '🇵🇹': ['Portugal ', ' Portuguese flag'],
  // '🇸🇷': ['Suriname ', ' Surinamese flag'],
  '👟': ['shoe ', ' sneakers ', ' gym shoe ', ' shoes ', ' sneaker ', ' gym shoes ', ' trainers'],
  '👠': ['shoe ', ' heels ', ' stilettos ', ' high heels ', ' high-heeled shoe ', ' shoes ', ' high-heeled shoes'],
  '♻️': ['recycle'],
  '👡': ['sandal ', ' sandals'],
  // '🇲🇼': ['Malawi ', ' Malawian flag'],
  // '🇸🇸': ['South Sudan ', ' South Sudanese flag'],
  '👢': ['boot ', ' boots'],
  '👣': ['footprints ', ' footprint'],
  // '🇲🇽': ['Mexico ', ' Mexican flag'],
  // '🇸🇹': [
  //   'São Tomé & Príncipe ',
  //   ' São Tomé and Príncipe ',
  //   ' Sao Tome & Principe ',
  //   ' Sao Tome and Principe ',
  //   ' São Toméan flag',
  // ],
  '☁️': ['cloud ', ' clouds'],
  '👨‍🔬': [
    'scientist ',
    ' chemist ',
    ' physicist ',
    ' lab technician ',
    ' rocket scientist ',
    ' man scientist ',
    ' man chemist ',
    ' man physicist ',
    ' man lab technician ',
    ' man rocket scientist',
  ],
  // '🇲🇾': ['Malaysia ', ' Malaysian flag'],
  // '🇵🇼': ['Palau ', ' Palauan flag'],
  '🙅‍♂️': [
    'not gonna happen ',
    ' not going to happen ',
    ' poor choice ',
    ' a no go ',
    ' denied ',
    ' rejected ',
    ' no deal',
  ],
  '✨': ['stars ', ' glitter ', ' twinkle ', ' sparkles ', ' glittering ', ' sparkling ', ' twinkling'],
  // '🇲🇿': ['Mozambique ', ' Mozambican flag'],
  // '🇸🇻': ['El Salvador ', ' Salvadorean flag'],
  // '🇵🇾': ['Paraguay ', ' Paraguayan flag'],
  // '🇻🇺': ['Vanuatu ', ' Vanuatuan flag'],
  '👰': ['bride ', ' wedding ', ' blushing bride ', ' getting married ', ' weddings ', ' brides ', ' blushing brides'],
  // '🇸🇽': ['Sint Maarten ', ' Sint Maarten flag'],
  // '🇾🇹': ['Mayotte ', ' Mahoran flag'],
  // '🇨🇦': ['Canada ', ' Canadian flag'],
  '🤽‍♂️': ['water polo ', ' water polo player ', ' playing water polo ', ' water sport ', ' man playing water polo'],
  '👴': ['old man ', ' grandpa ', ' grandfather ', ' papa ', ' grandad ', ' elderly man ', ' older man'],
  '👵': ['old woman ', ' grandma ', ' grandmother ', ' nanna ', ' elderly lady ', ' old lady'],
  // '🇸🇾': ['Syria ', ' Syrian flag'],
  '👶': [
    'baby ',
    ' kiddie ',
    ' kiddo ',
    ' babies ',
    ' kiddies ',
    ' kiddos ',
    ' child ',
    ' infant ',
    ' newborn ',
    ' children ',
    ' infants ',
    ' newborns',
  ],
  '👸': [
    'princess ',
    ' queen ',
    ' crown ',
    ' little princess ',
    ' pretty princess ',
    ' princesses ',
    ' queens ',
    ' little princesses ',
    ' pretty princesses ',
    ' your highness ',
    ' duchess ',
    ' beauty queen ',
    ' pageant queen ',
    ' tiara',
  ],
  '👹': ['Japanese ogre'],
  // '🇸🇿': ['Swaziland ', ' Swazi flag'],
  // '🇨🇨': ['Cocos (Keeling) Islands ', ' Cocos Island flag'],
  '👺': ['Japanese goblin'],
  '👻': ['ghost ', ' boo ', ' Halloween ', ' disappeared ', ' ghosted'],
  '👼': ['baby angel ', ' angel ', ' guardian angel ', ' baby angels ', ' angels ', ' guardian angels'],
  // '🇨🇩': ['Congo - Kinshasa ', ' Democratic Republic of the Congo ', ' Congolese flag'],
  '👽': ['alien ', ' extraterrestrial ', ' extraterrestrials ', ' Martians ', ' aliens ', ' Martian'],
  '🤹‍♀️': ['juggling ', ' woman juggling ', ' juggling balls ', ' juggler'],
  '❌': ['cross mark'],
  '💀': ['skull ', ' death ', ' dead'],
  '🅱️': ['blood type B'],
  '🧝‍♂️': ['elf ', ' man elf ', ' elves ', ' man elves ', ' Elrond ', ' Legolas'],
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿': ['England ', ' English flag'],
  '💃': [
    'dancer ',
    ' dancing woman ',
    ' woman dancing ',
    ' flamenco ',
    ' salsa ',
    ' dance ',
    ' dancing ',
    ' dancers ',
    ' disco',
  ],
  // '🇨🇫': ['Central African Republic ', ' Central African flag'],
  '♣️': ['playing card ', ' playing cards'],
  '💄': ['lipstick ', ' lipgloss ', ' makeup'],
  '💅': [
    'nail polish ',
    ' nail salon ',
    ' doing my nails ',
    ' nails done ',
    ' manicure ',
    ' getting my nails done ',
    ' painting my nails ',
    ' paint my nails ',
    ' get my nails done',
  ],
  '🀄️': ['mahjong ', ' mahjong tile'],
  // '🇨🇬': ['Congo - Brazzaville ', ' Republic of the Congo ', ' Congo Republic ', ' Congolese flag'],
  // '🇮🇨': ['Canary Islands ', ' Canary Island flag'],
  // '🇱🇦': ['Laos ', ' Laotian flag'],
  '🏌️‍♂️': ['golf ', ' golfer ', ' golfers ', ' golfing ', ' man golfing'],
  '🗡': ['sword ', ' swords ', ' dagger ', ' daggers'],
  // '🇨🇭': ['Switzerland ', ' Swiss flag'],
  // '🇮🇩': ['Indonesia ', ' Indonesian flag'],
  // '🇱🇧': ['Lebanon ', ' Lebanese flag'],
  '💋': ['kiss ', ' muah ', ' mwah ', ' xoxo ', ' xx'],
  '🧙‍♀️': [
    'mage ',
    ' mages ',
    ' magical ',
    ' enchanter ',
    ' enchanters ',
    ' necromancer ',
    ' necromancers ',
    ' woman mage ',
    ' sorceress ',
    ' sorceresses',
  ],
  '🧖‍♂️': ['man in sauna ', ' sauna ', ' steam room'],
  '💌': ['love letter'],
}
